name: spotlib
region: ams3

domains:
  - domain: codex.fm
    type: PRIMARY
    zone: codex.fm
  - domain: api.codex.fm
    type: ALIAS
    zone: codex.fm

ingress:
  rules:
    - component:
        name: api
      match:
        authority:
          exact: api.codex.fm
        path:
          prefix: /
    - component:
        name: frontend
      match:
        authority:
          exact: codex.fm
        path:
          prefix: /

services:
  # API Service
  - name: api
    dockerfile_path: backend/Dockerfile.api
    github:
      repo: RareSecond/libify
      branch: master
      deploy_on_push: true
    http_port: 3000
    instance_size_slug: basic-xs
    instance_count: 1
    health_check:
      http_path: /api/health
      timeout_seconds: 10
      port: 3000
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        type: SECRET
      - key: DATABASE_DIRECT_URL
        type: SECRET
      - key: REDIS_URL
        type: SECRET
      - key: JWT_SECRET
        type: SECRET
      - key: SPOTIFY_CLIENT_ID
        type: SECRET
      - key: SPOTIFY_CLIENT_SECRET
        type: SECRET
      - key: APP_URL
        value: https://api.codex.fm
      - key: FRONTEND_URL
        value: https://codex.fm

static_sites:
  - name: frontend
    github:
      repo: RareSecond/libify
      branch: master
      deploy_on_push: true
    source_dir: frontend
    catchall_document: index.html
    envs:
      - key: VITE_API_URL
        value: https://api.codex.fm

workers:
  # Worker Service
  - name: worker
    dockerfile_path: backend/Dockerfile.worker
    github:
      repo: RareSecond/libify
      branch: master
      deploy_on_push: true
    instance_size_slug: basic-xs
    instance_count: 1
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        type: SECRET
      - key: DATABASE_DIRECT_URL
        type: SECRET
      - key: REDIS_URL
        type: SECRET
      - key: JWT_SECRET
        type: SECRET
      - key: SPOTIFY_CLIENT_ID
        type: SECRET
      - key: SPOTIFY_CLIENT_SECRET
        type: SECRET
