# Production Docker Compose Configuration Override
# Usage: docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d
# Note: This file only contains production-specific overrides. The base configuration is in docker-compose.yml

version: '3.8'

services:
  # API with production optimizations
  api:
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=api"

  # Worker with auto-scaling
  worker:
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '1.5'
          memory: 1.5G
        reservations:
          cpus: '0.5'
          memory: 512M
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      SYNC_WORKER_CONCURRENCY: 2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=worker"

  # Redis with persistence and memory management
  redis:
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    sysctls:
      - net.core.somaxconn=511
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

