/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/~__root'
import { Route as TracksImport } from './routes/~tracks'
import { Route as PlaylistsImport } from './routes/~playlists'
import { Route as IndexImport } from './routes/~index'
import { Route as PlaylistsIndexImport } from './routes/~playlists.index'
import { Route as PlaylistsIdImport } from './routes/~playlists.$id'
import { Route as AuthSuccessImport } from './routes/~auth/~success'

// Create/Update Routes

const TracksRoute = TracksImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistsRoute = PlaylistsImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistsIndexRoute = PlaylistsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaylistsRoute,
} as any)

const PlaylistsIdRoute = PlaylistsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlaylistsRoute,
} as any)

const AuthSuccessRoute = AuthSuccessImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsImport
      parentRoute: typeof rootRoute
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksImport
      parentRoute: typeof rootRoute
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessImport
      parentRoute: typeof rootRoute
    }
    '/playlists/$id': {
      id: '/playlists/$id'
      path: '/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof PlaylistsIdImport
      parentRoute: typeof PlaylistsImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexImport
      parentRoute: typeof PlaylistsImport
    }
  }
}

// Create and export the route tree

interface PlaylistsRouteChildren {
  PlaylistsIdRoute: typeof PlaylistsIdRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
}

const PlaylistsRouteChildren: PlaylistsRouteChildren = {
  PlaylistsIdRoute: PlaylistsIdRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
}

const PlaylistsRouteWithChildren = PlaylistsRoute._addFileChildren(
  PlaylistsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/tracks': typeof TracksRoute
  '/auth/success': typeof AuthSuccessRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/playlists/': typeof PlaylistsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tracks': typeof TracksRoute
  '/auth/success': typeof AuthSuccessRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/playlists': typeof PlaylistsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/tracks': typeof TracksRoute
  '/auth/success': typeof AuthSuccessRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/playlists/': typeof PlaylistsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playlists'
    | '/tracks'
    | '/auth/success'
    | '/playlists/$id'
    | '/playlists/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tracks' | '/auth/success' | '/playlists/$id' | '/playlists'
  id:
    | '__root__'
    | '/'
    | '/playlists'
    | '/tracks'
    | '/auth/success'
    | '/playlists/$id'
    | '/playlists/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaylistsRoute: typeof PlaylistsRouteWithChildren
  TracksRoute: typeof TracksRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaylistsRoute: PlaylistsRouteWithChildren,
  TracksRoute: TracksRoute,
  AuthSuccessRoute: AuthSuccessRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/",
        "/playlists",
        "/tracks",
        "/auth/success"
      ]
    },
    "/": {
      "filePath": "~index.tsx"
    },
    "/playlists": {
      "filePath": "~playlists.tsx",
      "children": [
        "/playlists/$id",
        "/playlists/"
      ]
    },
    "/tracks": {
      "filePath": "~tracks.tsx"
    },
    "/auth/success": {
      "filePath": "~auth/~success.tsx"
    },
    "/playlists/$id": {
      "filePath": "~playlists.$id.tsx",
      "parent": "/playlists"
    },
    "/playlists/": {
      "filePath": "~playlists.index.tsx",
      "parent": "/playlists"
    }
  }
}
ROUTE_MANIFEST_END */
