-- AlterTable: Remove artist-level genres (replaced by track-level genres)
ALTER TABLE "SpotifyArtist" DROP COLUMN IF EXISTS "genres";

-- AlterTable
ALTER TABLE "SpotifyTrack" ADD COLUMN     "genresUpdatedAt" TIMESTAMP(3);

-- CreateTable
CREATE TABLE "Genre" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "displayName" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Genre_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TrackGenre" (
    "trackId" TEXT NOT NULL,
    "genreId" TEXT NOT NULL,
    "weight" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TrackGenre_pkey" PRIMARY KEY ("trackId","genreId")
);

-- CreateIndex
CREATE UNIQUE INDEX "Genre_name_key" ON "Genre"("name");

-- CreateIndex
CREATE INDEX "TrackGenre_genreId_idx" ON "TrackGenre"("genreId");

-- CreateIndex
CREATE INDEX "TrackGenre_trackId_idx" ON "TrackGenre"("trackId");

-- AddForeignKey
ALTER TABLE "TrackGenre" ADD CONSTRAINT "TrackGenre_trackId_fkey" FOREIGN KEY ("trackId") REFERENCES "SpotifyTrack"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TrackGenre" ADD CONSTRAINT "TrackGenre_genreId_fkey" FOREIGN KEY ("genreId") REFERENCES "Genre"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- Seed genre whitelist (beets 1546 genres)
INSERT INTO "Genre" (id, name, "displayName", "createdAt") VALUES
  (gen_random_uuid(), '2 tone', '2 Tone', NOW()),
  (gen_random_uuid(), '2-step garage', '2-step Garage', NOW()),
  (gen_random_uuid(), '4-beat', '4-beat', NOW()),
  (gen_random_uuid(), '4x4 garage', '4x4 Garage', NOW()),
  (gen_random_uuid(), '8-bit', '8-bit', NOW()),
  (gen_random_uuid(), 'acapella', 'Acapella', NOW()),
  (gen_random_uuid(), 'acid', 'Acid', NOW()),
  (gen_random_uuid(), 'acid breaks', 'Acid Breaks', NOW()),
  (gen_random_uuid(), 'acid house', 'Acid House', NOW()),
  (gen_random_uuid(), 'acid jazz', 'Acid Jazz', NOW()),
  (gen_random_uuid(), 'acid rock', 'Acid Rock', NOW()),
  (gen_random_uuid(), 'acoustic music', 'Acoustic Music', NOW()),
  (gen_random_uuid(), 'acousticana', 'Acousticana', NOW()),
  (gen_random_uuid(), 'adult contemporary music', 'Adult Contemporary Music', NOW()),
  (gen_random_uuid(), 'african popular music', 'African Popular Music', NOW()),
  (gen_random_uuid(), 'african rumba', 'African Rumba', NOW()),
  (gen_random_uuid(), 'afrobeat', 'Afrobeat', NOW()),
  (gen_random_uuid(), 'aleatoric music', 'Aleatoric Music', NOW()),
  (gen_random_uuid(), 'alternative country', 'Alternative Country', NOW()),
  (gen_random_uuid(), 'alternative dance', 'Alternative Dance', NOW()),
  (gen_random_uuid(), 'alternative hip hop', 'Alternative Hip Hop', NOW()),
  (gen_random_uuid(), 'alternative metal', 'Alternative Metal', NOW()),
  (gen_random_uuid(), 'alternative rock', 'Alternative Rock', NOW()),
  (gen_random_uuid(), 'ambient', 'Ambient', NOW()),
  (gen_random_uuid(), 'ambient house', 'Ambient House', NOW()),
  (gen_random_uuid(), 'ambient music', 'Ambient Music', NOW()),
  (gen_random_uuid(), 'americana', 'Americana', NOW()),
  (gen_random_uuid(), 'anarcho punk', 'Anarcho Punk', NOW()),
  (gen_random_uuid(), 'anti-folk', 'Anti-folk', NOW()),
  (gen_random_uuid(), 'apala', 'Apala', NOW()),
  (gen_random_uuid(), 'ape haters', 'Ape Haters', NOW()),
  (gen_random_uuid(), 'arab pop', 'Arab Pop', NOW()),
  (gen_random_uuid(), 'arabesque', 'Arabesque', NOW()),
  (gen_random_uuid(), 'arabic pop', 'Arabic Pop', NOW()),
  (gen_random_uuid(), 'argentine rock', 'Argentine Rock', NOW()),
  (gen_random_uuid(), 'ars antiqua', 'Ars Antiqua', NOW()),
  (gen_random_uuid(), 'ars nova', 'Ars Nova', NOW()),
  (gen_random_uuid(), 'art punk', 'Art Punk', NOW()),
  (gen_random_uuid(), 'art rock', 'Art Rock', NOW()),
  (gen_random_uuid(), 'ashiq', 'Ashiq', NOW()),
  (gen_random_uuid(), 'asian american jazz', 'Asian American Jazz', NOW()),
  (gen_random_uuid(), 'australian country music', 'Australian Country Music', NOW()),
  (gen_random_uuid(), 'australian hip hop', 'Australian Hip Hop', NOW()),
  (gen_random_uuid(), 'australian pub rock', 'Australian Pub Rock', NOW()),
  (gen_random_uuid(), 'austropop', 'Austropop', NOW()),
  (gen_random_uuid(), 'avant-garde', 'Avant-garde', NOW()),
  (gen_random_uuid(), 'avant-garde jazz', 'Avant-garde Jazz', NOW()),
  (gen_random_uuid(), 'avant-garde metal', 'Avant-garde Metal', NOW()),
  (gen_random_uuid(), 'avant-garde music', 'Avant-garde Music', NOW()),
  (gen_random_uuid(), 'axé', 'Axé', NOW()),
  (gen_random_uuid(), 'bac-bal', 'Bac-bal', NOW()),
  (gen_random_uuid(), 'bachata', 'Bachata', NOW()),
  (gen_random_uuid(), 'baggy', 'Baggy', NOW()),
  (gen_random_uuid(), 'baila', 'Baila', NOW()),
  (gen_random_uuid(), 'baile funk', 'Baile Funk', NOW()),
  (gen_random_uuid(), 'baisha xiyue', 'Baisha Xiyue', NOW()),
  (gen_random_uuid(), 'baithak gana', 'Baithak Gana', NOW()),
  (gen_random_uuid(), 'baião', 'Baião', NOW()),
  (gen_random_uuid(), 'bajourou', 'Bajourou', NOW()),
  (gen_random_uuid(), 'bakersfield sound', 'Bakersfield Sound', NOW()),
  (gen_random_uuid(), 'bakou', 'Bakou', NOW()),
  (gen_random_uuid(), 'bakshy', 'Bakshy', NOW()),
  (gen_random_uuid(), 'bal-musette', 'Bal-musette', NOW()),
  (gen_random_uuid(), 'balakadri', 'Balakadri', NOW()),
  (gen_random_uuid(), 'balinese gamelan', 'Balinese Gamelan', NOW()),
  (gen_random_uuid(), 'balkan pop', 'Balkan Pop', NOW()),
  (gen_random_uuid(), 'ballad', 'Ballad', NOW()),
  (gen_random_uuid(), 'ballata', 'Ballata', NOW()),
  (gen_random_uuid(), 'ballet', 'Ballet', NOW()),
  (gen_random_uuid(), 'bamboo band', 'Bamboo Band', NOW()),
  (gen_random_uuid(), 'bambuco', 'Bambuco', NOW()),
  (gen_random_uuid(), 'banda', 'Banda', NOW()),
  (gen_random_uuid(), 'bangsawan', 'Bangsawan', NOW()),
  (gen_random_uuid(), 'bantowbol', 'Bantowbol', NOW()),
  (gen_random_uuid(), 'barbershop music', 'Barbershop Music', NOW()),
  (gen_random_uuid(), 'barndance', 'Barndance', NOW()),
  (gen_random_uuid(), 'baroque', 'Baroque', NOW()),
  (gen_random_uuid(), 'baroque music', 'Baroque Music', NOW()),
  (gen_random_uuid(), 'baroque pop', 'Baroque Pop', NOW()),
  (gen_random_uuid(), 'bass music', 'Bass Music', NOW()),
  (gen_random_uuid(), 'batcave', 'Batcave', NOW()),
  (gen_random_uuid(), 'batucada', 'Batucada', NOW()),
  (gen_random_uuid(), 'batuco', 'Batuco', NOW()),
  (gen_random_uuid(), 'batá-rumba', 'Batá-rumba', NOW()),
  (gen_random_uuid(), 'beach music', 'Beach Music', NOW()),
  (gen_random_uuid(), 'beat', 'Beat', NOW()),
  (gen_random_uuid(), 'beatboxing', 'Beatboxing', NOW()),
  (gen_random_uuid(), 'beautiful music', 'Beautiful Music', NOW()),
  (gen_random_uuid(), 'bebop', 'Bebop', NOW()),
  (gen_random_uuid(), 'beiguan', 'Beiguan', NOW()),
  (gen_random_uuid(), 'bel canto', 'Bel Canto', NOW()),
  (gen_random_uuid(), 'bend-skin', 'Bend-skin', NOW()),
  (gen_random_uuid(), 'benga', 'Benga', NOW()),
  (gen_random_uuid(), 'berlin school of electronic music', 'Berlin School Of Electronic Music', NOW()),
  (gen_random_uuid(), 'bhajan', 'Bhajan', NOW()),
  (gen_random_uuid(), 'bhangra', 'Bhangra', NOW()),
  (gen_random_uuid(), 'bhangra-wine', 'Bhangra-wine', NOW()),
  (gen_random_uuid(), 'bhangragga', 'Bhangragga', NOW()),
  (gen_random_uuid(), 'bhangramuffin', 'Bhangramuffin', NOW()),
  (gen_random_uuid(), 'big band', 'Big Band', NOW()),
  (gen_random_uuid(), 'big band music', 'Big Band Music', NOW()),
  (gen_random_uuid(), 'big beat', 'Big Beat', NOW()),
  (gen_random_uuid(), 'biguine', 'Biguine', NOW()),
  (gen_random_uuid(), 'bihu', 'Bihu', NOW()),
  (gen_random_uuid(), 'bikutsi', 'Bikutsi', NOW()),
  (gen_random_uuid(), 'biomusic', 'Biomusic', NOW()),
  (gen_random_uuid(), 'bitcore', 'Bitcore', NOW()),
  (gen_random_uuid(), 'bitpop', 'Bitpop', NOW()),
  (gen_random_uuid(), 'black metal', 'Black Metal', NOW()),
  (gen_random_uuid(), 'blackened death metal', 'Blackened Death Metal', NOW()),
  (gen_random_uuid(), 'blue-eyed soul', 'Blue-eyed Soul', NOW()),
  (gen_random_uuid(), 'bluegrass', 'Bluegrass', NOW()),
  (gen_random_uuid(), 'blues', 'Blues', NOW()),
  (gen_random_uuid(), 'blues ballad', 'Blues Ballad', NOW()),
  (gen_random_uuid(), 'blues-rock', 'Blues-rock', NOW()),
  (gen_random_uuid(), 'boogie', 'Boogie', NOW()),
  (gen_random_uuid(), 'boogie woogie', 'Boogie Woogie', NOW()),
  (gen_random_uuid(), 'boogie-woogie', 'Boogie-woogie', NOW()),
  (gen_random_uuid(), 'bossa nova', 'Bossa Nova', NOW()),
  (gen_random_uuid(), 'brass band', 'Brass Band', NOW()),
  (gen_random_uuid(), 'brazilian funk', 'Brazilian Funk', NOW()),
  (gen_random_uuid(), 'brazilian jazz', 'Brazilian Jazz', NOW()),
  (gen_random_uuid(), 'breakbeat', 'Breakbeat', NOW()),
  (gen_random_uuid(), 'breakbeat hardcore', 'Breakbeat Hardcore', NOW()),
  (gen_random_uuid(), 'breakcore', 'Breakcore', NOW()),
  (gen_random_uuid(), 'breton music', 'Breton Music', NOW()),
  (gen_random_uuid(), 'brill building pop', 'Brill Building Pop', NOW()),
  (gen_random_uuid(), 'britfunk', 'Britfunk', NOW()),
  (gen_random_uuid(), 'british blues', 'British Blues', NOW()),
  (gen_random_uuid(), 'british invasion', 'British Invasion', NOW()),
  (gen_random_uuid(), 'britpop', 'Britpop', NOW()),
  (gen_random_uuid(), 'broken beat', 'Broken Beat', NOW()),
  (gen_random_uuid(), 'brown-eyed soul', 'Brown-eyed Soul', NOW()),
  (gen_random_uuid(), 'brukdown', 'Brukdown', NOW()),
  (gen_random_uuid(), 'brutal death metal', 'Brutal Death Metal', NOW()),
  (gen_random_uuid(), 'bubblegum dance', 'Bubblegum Dance', NOW()),
  (gen_random_uuid(), 'bubblegum pop', 'Bubblegum Pop', NOW()),
  (gen_random_uuid(), 'bulerias', 'Bulerias', NOW()),
  (gen_random_uuid(), 'bumba-meu-boi', 'Bumba-meu-boi', NOW()),
  (gen_random_uuid(), 'bunraku', 'Bunraku', NOW()),
  (gen_random_uuid(), 'burger-highlife', 'Burger-highlife', NOW()),
  (gen_random_uuid(), 'burgundian school', 'Burgundian School', NOW()),
  (gen_random_uuid(), 'byzantine chant', 'Byzantine Chant', NOW()),
  (gen_random_uuid(), 'ca din tulnic', 'Ca Din Tulnic', NOW()),
  (gen_random_uuid(), 'ca pe lunca', 'Ca Pe Lunca', NOW()),
  (gen_random_uuid(), 'ca trù', 'Ca Trù', NOW()),
  (gen_random_uuid(), 'cabaret', 'Cabaret', NOW()),
  (gen_random_uuid(), 'cadence', 'Cadence', NOW()),
  (gen_random_uuid(), 'cadence rampa', 'Cadence Rampa', NOW()),
  (gen_random_uuid(), 'cadence-lypso', 'Cadence-lypso', NOW()),
  (gen_random_uuid(), 'café-aman', 'Café-aman', NOW()),
  (gen_random_uuid(), 'cai luong', 'Cai Luong', NOW()),
  (gen_random_uuid(), 'cajun music', 'Cajun Music', NOW()),
  (gen_random_uuid(), 'cakewalk', 'Cakewalk', NOW()),
  (gen_random_uuid(), 'calenda', 'Calenda', NOW()),
  (gen_random_uuid(), 'calentanos', 'Calentanos', NOW()),
  (gen_random_uuid(), 'calgia', 'Calgia', NOW()),
  (gen_random_uuid(), 'calypso', 'Calypso', NOW()),
  (gen_random_uuid(), 'calypso jazz', 'Calypso Jazz', NOW()),
  (gen_random_uuid(), 'calypso-style baila', 'Calypso-style Baila', NOW()),
  (gen_random_uuid(), 'campursari', 'Campursari', NOW()),
  (gen_random_uuid(), 'canatronic', 'Canatronic', NOW()),
  (gen_random_uuid(), 'canción de autor', 'Canción De Autor', NOW()),
  (gen_random_uuid(), 'candombe', 'Candombe', NOW()),
  (gen_random_uuid(), 'canon', 'Canon', NOW()),
  (gen_random_uuid(), 'canrock', 'Canrock', NOW()),
  (gen_random_uuid(), 'cantata', 'Cantata', NOW()),
  (gen_random_uuid(), 'cantautorato', 'Cantautorato', NOW()),
  (gen_random_uuid(), 'cantautor', 'Cantautor', NOW()),
  (gen_random_uuid(), 'cantautora', 'Cantautora', NOW()),
  (gen_random_uuid(), 'cante chico', 'Cante Chico', NOW()),
  (gen_random_uuid(), 'cante jondo', 'Cante Jondo', NOW()),
  (gen_random_uuid(), 'canterbury scene', 'Canterbury Scene', NOW()),
  (gen_random_uuid(), 'cantiga', 'Cantiga', NOW()),
  (gen_random_uuid(), 'cantique', 'Cantique', NOW()),
  (gen_random_uuid(), 'cantiñas', 'Cantiñas', NOW()),
  (gen_random_uuid(), 'canto livre', 'Canto Livre', NOW()),
  (gen_random_uuid(), 'canto nuevo', 'Canto Nuevo', NOW()),
  (gen_random_uuid(), 'canto popular', 'Canto Popular', NOW()),
  (gen_random_uuid(), 'cantopop', 'Cantopop', NOW()),
  (gen_random_uuid(), 'canzone napoletana', 'Canzone Napoletana', NOW()),
  (gen_random_uuid(), 'cape jazz', 'Cape Jazz', NOW()),
  (gen_random_uuid(), 'capoeira music', 'Capoeira Music', NOW()),
  (gen_random_uuid(), 'caracoles', 'Caracoles', NOW()),
  (gen_random_uuid(), 'carceleras', 'Carceleras', NOW()),
  (gen_random_uuid(), 'cardas', 'Cardas', NOW()),
  (gen_random_uuid(), 'cardiowave', 'Cardiowave', NOW()),
  (gen_random_uuid(), 'carimbó', 'Carimbó', NOW()),
  (gen_random_uuid(), 'cariso', 'Cariso', NOW()),
  (gen_random_uuid(), 'carnatic music', 'Carnatic Music', NOW()),
  (gen_random_uuid(), 'carol', 'Carol', NOW()),
  (gen_random_uuid(), 'cartageneras', 'Cartageneras', NOW()),
  (gen_random_uuid(), 'cassette culture', 'Cassette Culture', NOW()),
  (gen_random_uuid(), 'casséy-co', 'Casséy-co', NOW()),
  (gen_random_uuid(), 'cavacha', 'Cavacha', NOW()),
  (gen_random_uuid(), 'caveman', 'Caveman', NOW()),
  (gen_random_uuid(), 'caña', 'Caña', NOW()),
  (gen_random_uuid(), 'celempungan', 'Celempungan', NOW()),
  (gen_random_uuid(), 'cello rock', 'Cello Rock', NOW()),
  (gen_random_uuid(), 'celtic', 'Celtic', NOW()),
  (gen_random_uuid(), 'celtic fusion', 'Celtic Fusion', NOW()),
  (gen_random_uuid(), 'celtic metal', 'Celtic Metal', NOW()),
  (gen_random_uuid(), 'celtic punk', 'Celtic Punk', NOW()),
  (gen_random_uuid(), 'celtic reggae', 'Celtic Reggae', NOW()),
  (gen_random_uuid(), 'celtic rock', 'Celtic Rock', NOW()),
  (gen_random_uuid(), 'cha-cha-cha', 'Cha-cha-cha', NOW()),
  (gen_random_uuid(), 'chakacha', 'Chakacha', NOW()),
  (gen_random_uuid(), 'chalga', 'Chalga', NOW()),
  (gen_random_uuid(), 'chamamé', 'Chamamé', NOW()),
  (gen_random_uuid(), 'chamber jazz', 'Chamber Jazz', NOW()),
  (gen_random_uuid(), 'chamber music', 'Chamber Music', NOW()),
  (gen_random_uuid(), 'chamber pop', 'Chamber Pop', NOW()),
  (gen_random_uuid(), 'champeta', 'Champeta', NOW()),
  (gen_random_uuid(), 'changuí', 'Changuí', NOW()),
  (gen_random_uuid(), 'chanson', 'Chanson', NOW()),
  (gen_random_uuid(), 'chant', 'Chant', NOW()),
  (gen_random_uuid(), 'charanga', 'Charanga', NOW()),
  (gen_random_uuid(), 'charanga-vallenata', 'Charanga-vallenata', NOW()),
  (gen_random_uuid(), 'charikawi', 'Charikawi', NOW()),
  (gen_random_uuid(), 'chastushki', 'Chastushki', NOW()),
  (gen_random_uuid(), 'chau van', 'Chau Van', NOW()),
  (gen_random_uuid(), 'chemical breaks', 'Chemical Breaks', NOW()),
  (gen_random_uuid(), 'chicago blues', 'Chicago Blues', NOW()),
  (gen_random_uuid(), 'chicago house', 'Chicago House', NOW()),
  (gen_random_uuid(), 'chicago soul', 'Chicago Soul', NOW()),
  (gen_random_uuid(), 'chicano rap', 'Chicano Rap', NOW()),
  (gen_random_uuid(), 'chicha', 'Chicha', NOW()),
  (gen_random_uuid(), 'chicken scratch', 'Chicken Scratch', NOW()),
  (gen_random_uuid(), 'children''s music', 'Children''s Music', NOW()),
  (gen_random_uuid(), 'chillout', 'Chillout', NOW()),
  (gen_random_uuid(), 'chillwave', 'Chillwave', NOW()),
  (gen_random_uuid(), 'chimurenga', 'Chimurenga', NOW()),
  (gen_random_uuid(), 'chinese music', 'Chinese Music', NOW()),
  (gen_random_uuid(), 'chinese pop', 'Chinese Pop', NOW()),
  (gen_random_uuid(), 'chinese rock', 'Chinese Rock', NOW()),
  (gen_random_uuid(), 'chip music', 'Chip Music', NOW()),
  (gen_random_uuid(), 'cho-kantrum', 'Cho-kantrum', NOW()),
  (gen_random_uuid(), 'chongak', 'Chongak', NOW()),
  (gen_random_uuid(), 'chopera', 'Chopera', NOW()),
  (gen_random_uuid(), 'chorinho', 'Chorinho', NOW()),
  (gen_random_uuid(), 'choro', 'Choro', NOW()),
  (gen_random_uuid(), 'chouval bwa', 'Chouval Bwa', NOW()),
  (gen_random_uuid(), 'chowtal', 'Chowtal', NOW()),
  (gen_random_uuid(), 'christian alternative', 'Christian Alternative', NOW()),
  (gen_random_uuid(), 'christian black metal', 'Christian Black Metal', NOW()),
  (gen_random_uuid(), 'christian electronic music', 'Christian Electronic Music', NOW()),
  (gen_random_uuid(), 'christian hardcore', 'Christian Hardcore', NOW()),
  (gen_random_uuid(), 'christian hip hop', 'Christian Hip Hop', NOW()),
  (gen_random_uuid(), 'christian industrial', 'Christian Industrial', NOW()),
  (gen_random_uuid(), 'christian metal', 'Christian Metal', NOW()),
  (gen_random_uuid(), 'christian music', 'Christian Music', NOW()),
  (gen_random_uuid(), 'christian punk', 'Christian Punk', NOW()),
  (gen_random_uuid(), 'christian r&b', 'Christian R&b', NOW()),
  (gen_random_uuid(), 'christian rock', 'Christian Rock', NOW()),
  (gen_random_uuid(), 'christian ska', 'Christian Ska', NOW()),
  (gen_random_uuid(), 'christmas carol', 'Christmas Carol', NOW()),
  (gen_random_uuid(), 'christmas music', 'Christmas Music', NOW()),
  (gen_random_uuid(), 'chumba', 'Chumba', NOW()),
  (gen_random_uuid(), 'chut-kai-pang', 'Chut-kai-pang', NOW()),
  (gen_random_uuid(), 'chutney', 'Chutney', NOW()),
  (gen_random_uuid(), 'chutney soca', 'Chutney Soca', NOW()),
  (gen_random_uuid(), 'chutney-bhangra', 'Chutney-bhangra', NOW()),
  (gen_random_uuid(), 'chutney-hip hop', 'Chutney-hip Hop', NOW()),
  (gen_random_uuid(), 'chutney-soca', 'Chutney-soca', NOW()),
  (gen_random_uuid(), 'chylandyk', 'Chylandyk', NOW()),
  (gen_random_uuid(), 'chzalni', 'Chzalni', NOW()),
  (gen_random_uuid(), 'chèo', 'Chèo', NOW()),
  (gen_random_uuid(), 'cigányzene', 'Cigányzene', NOW()),
  (gen_random_uuid(), 'classic', 'Classic', NOW()),
  (gen_random_uuid(), 'classic country', 'Classic Country', NOW()),
  (gen_random_uuid(), 'classic female blues', 'Classic Female Blues', NOW()),
  (gen_random_uuid(), 'classic rock', 'Classic Rock', NOW()),
  (gen_random_uuid(), 'classical', 'Classical', NOW()),
  (gen_random_uuid(), 'classical music', 'Classical Music', NOW()),
  (gen_random_uuid(), 'classical music era', 'Classical Music Era', NOW()),
  (gen_random_uuid(), 'clicks n cuts', 'Clicks N Cuts', NOW()),
  (gen_random_uuid(), 'close harmony', 'Close Harmony', NOW()),
  (gen_random_uuid(), 'club music', 'Club Music', NOW()),
  (gen_random_uuid(), 'cocobale', 'Cocobale', NOW()),
  (gen_random_uuid(), 'coimbra fado', 'Coimbra Fado', NOW()),
  (gen_random_uuid(), 'coladeira', 'Coladeira', NOW()),
  (gen_random_uuid(), 'colombianas', 'Colombianas', NOW()),
  (gen_random_uuid(), 'combined rhythm', 'Combined Rhythm', NOW()),
  (gen_random_uuid(), 'comedy', 'Comedy', NOW()),
  (gen_random_uuid(), 'comedy rap', 'Comedy Rap', NOW()),
  (gen_random_uuid(), 'comedy rock', 'Comedy Rock', NOW()),
  (gen_random_uuid(), 'comic opera', 'Comic Opera', NOW()),
  (gen_random_uuid(), 'comparsa', 'Comparsa', NOW()),
  (gen_random_uuid(), 'compas direct', 'Compas Direct', NOW()),
  (gen_random_uuid(), 'compas meringue', 'Compas Meringue', NOW()),
  (gen_random_uuid(), 'concert overture', 'Concert Overture', NOW()),
  (gen_random_uuid(), 'concerto', 'Concerto', NOW()),
  (gen_random_uuid(), 'concerto grosso', 'Concerto Grosso', NOW()),
  (gen_random_uuid(), 'congo', 'Congo', NOW()),
  (gen_random_uuid(), 'conjunto', 'Conjunto', NOW()),
  (gen_random_uuid(), 'contemporary christian', 'Contemporary Christian', NOW()),
  (gen_random_uuid(), 'contemporary christian music', 'Contemporary Christian Music', NOW()),
  (gen_random_uuid(), 'contemporary classical', 'Contemporary Classical', NOW()),
  (gen_random_uuid(), 'contemporary r&b', 'Contemporary R&b', NOW()),
  (gen_random_uuid(), 'contonbley', 'Contonbley', NOW()),
  (gen_random_uuid(), 'contradanza', 'Contradanza', NOW()),
  (gen_random_uuid(), 'cool jazz', 'Cool Jazz', NOW()),
  (gen_random_uuid(), 'corrido', 'Corrido', NOW()),
  (gen_random_uuid(), 'corsican polyphonic song', 'Corsican Polyphonic Song', NOW()),
  (gen_random_uuid(), 'cothoza mfana', 'Cothoza Mfana', NOW()),
  (gen_random_uuid(), 'country', 'Country', NOW()),
  (gen_random_uuid(), 'country blues', 'Country Blues', NOW()),
  (gen_random_uuid(), 'country gospel', 'Country Gospel', NOW()),
  (gen_random_uuid(), 'country music', 'Country Music', NOW()),
  (gen_random_uuid(), 'country pop', 'Country Pop', NOW()),
  (gen_random_uuid(), 'country r&b', 'Country R&b', NOW()),
  (gen_random_uuid(), 'country rock', 'Country Rock', NOW()),
  (gen_random_uuid(), 'country-rap', 'Country-rap', NOW()),
  (gen_random_uuid(), 'countrypolitan', 'Countrypolitan', NOW()),
  (gen_random_uuid(), 'couple de sonneurs', 'Couple De Sonneurs', NOW()),
  (gen_random_uuid(), 'coupé-décalé', 'Coupé-décalé', NOW()),
  (gen_random_uuid(), 'cowpunk', 'Cowpunk', NOW()),
  (gen_random_uuid(), 'cretan music', 'Cretan Music', NOW()),
  (gen_random_uuid(), 'crossover jazz', 'Crossover Jazz', NOW()),
  (gen_random_uuid(), 'crossover music', 'Crossover Music', NOW()),
  (gen_random_uuid(), 'crossover thrash', 'Crossover Thrash', NOW()),
  (gen_random_uuid(), 'crossover thrash metal', 'Crossover Thrash Metal', NOW()),
  (gen_random_uuid(), 'crunk', 'Crunk', NOW()),
  (gen_random_uuid(), 'crunk&b', 'Crunk&b', NOW()),
  (gen_random_uuid(), 'crunkcore', 'Crunkcore', NOW()),
  (gen_random_uuid(), 'crust punk', 'Crust Punk', NOW()),
  (gen_random_uuid(), 'csárdás', 'Csárdás', NOW()),
  (gen_random_uuid(), 'cuarteto', 'Cuarteto', NOW()),
  (gen_random_uuid(), 'cuban rumba', 'Cuban Rumba', NOW()),
  (gen_random_uuid(), 'cuddlecore', 'Cuddlecore', NOW()),
  (gen_random_uuid(), 'cueca', 'Cueca', NOW()),
  (gen_random_uuid(), 'cumbia', 'Cumbia', NOW()),
  (gen_random_uuid(), 'cumbia villera', 'Cumbia Villera', NOW()),
  (gen_random_uuid(), 'cybergrind', 'Cybergrind', NOW()),
  (gen_random_uuid(), 'dabka', 'Dabka', NOW()),
  (gen_random_uuid(), 'dadra', 'Dadra', NOW()),
  (gen_random_uuid(), 'daina', 'Daina', NOW()),
  (gen_random_uuid(), 'dalauna', 'Dalauna', NOW()),
  (gen_random_uuid(), 'dance', 'Dance', NOW()),
  (gen_random_uuid(), 'dance music', 'Dance Music', NOW()),
  (gen_random_uuid(), 'dance-pop', 'Dance-pop', NOW()),
  (gen_random_uuid(), 'dance-punk', 'Dance-punk', NOW()),
  (gen_random_uuid(), 'dance-rock', 'Dance-rock', NOW()),
  (gen_random_uuid(), 'dancehall', 'Dancehall', NOW()),
  (gen_random_uuid(), 'dangdut', 'Dangdut', NOW()),
  (gen_random_uuid(), 'danger music', 'Danger Music', NOW()),
  (gen_random_uuid(), 'dansband', 'Dansband', NOW()),
  (gen_random_uuid(), 'danza', 'Danza', NOW()),
  (gen_random_uuid(), 'danzón', 'Danzón', NOW()),
  (gen_random_uuid(), 'dark ambient', 'Dark Ambient', NOW()),
  (gen_random_uuid(), 'dark cabaret', 'Dark Cabaret', NOW()),
  (gen_random_uuid(), 'dark pop', 'Dark Pop', NOW()),
  (gen_random_uuid(), 'darkcore', 'Darkcore', NOW()),
  (gen_random_uuid(), 'darkstep', 'Darkstep', NOW()),
  (gen_random_uuid(), 'darkwave', 'Darkwave', NOW()),
  (gen_random_uuid(), 'de ascultat la servici', 'De Ascultat La Servici', NOW()),
  (gen_random_uuid(), 'de codru', 'De Codru', NOW()),
  (gen_random_uuid(), 'de dragoste', 'De Dragoste', NOW()),
  (gen_random_uuid(), 'de jale', 'De Jale', NOW()),
  (gen_random_uuid(), 'de pahar', 'De Pahar', NOW()),
  (gen_random_uuid(), 'death industrial', 'Death Industrial', NOW()),
  (gen_random_uuid(), 'death metal', 'Death Metal', NOW()),
  (gen_random_uuid(), 'death rock', 'Death Rock', NOW()),
  (gen_random_uuid(), 'death/doom', 'Death/doom', NOW()),
  (gen_random_uuid(), 'deathcore', 'Deathcore', NOW()),
  (gen_random_uuid(), 'deathgrind', 'Deathgrind', NOW()),
  (gen_random_uuid(), 'deathrock', 'Deathrock', NOW()),
  (gen_random_uuid(), 'deep funk', 'Deep Funk', NOW()),
  (gen_random_uuid(), 'deep house', 'Deep House', NOW()),
  (gen_random_uuid(), 'deep soul', 'Deep Soul', NOW()),
  (gen_random_uuid(), 'degung', 'Degung', NOW()),
  (gen_random_uuid(), 'delta blues', 'Delta Blues', NOW()),
  (gen_random_uuid(), 'dementia', 'Dementia', NOW()),
  (gen_random_uuid(), 'desert rock', 'Desert Rock', NOW()),
  (gen_random_uuid(), 'desi', 'Desi', NOW()),
  (gen_random_uuid(), 'detroit blues', 'Detroit Blues', NOW()),
  (gen_random_uuid(), 'detroit techno', 'Detroit Techno', NOW()),
  (gen_random_uuid(), 'dub techno', 'Dub Techno', NOW()),
  (gen_random_uuid(), 'dhamar', 'Dhamar', NOW()),
  (gen_random_uuid(), 'dhimotiká', 'Dhimotiká', NOW()),
  (gen_random_uuid(), 'dhrupad', 'Dhrupad', NOW()),
  (gen_random_uuid(), 'dhun', 'Dhun', NOW()),
  (gen_random_uuid(), 'digital hardcore', 'Digital Hardcore', NOW()),
  (gen_random_uuid(), 'dirge', 'Dirge', NOW()),
  (gen_random_uuid(), 'dirty dutch', 'Dirty Dutch', NOW()),
  (gen_random_uuid(), 'dirty rap', 'Dirty Rap', NOW()),
  (gen_random_uuid(), 'dirty rap/pornocore', 'Dirty Rap/pornocore', NOW()),
  (gen_random_uuid(), 'dirty south', 'Dirty South', NOW()),
  (gen_random_uuid(), 'disco', 'Disco', NOW()),
  (gen_random_uuid(), 'disco house', 'Disco House', NOW()),
  (gen_random_uuid(), 'disco polo', 'Disco Polo', NOW()),
  (gen_random_uuid(), 'disney', 'Disney', NOW()),
  (gen_random_uuid(), 'disney hardcore', 'Disney Hardcore', NOW()),
  (gen_random_uuid(), 'disney pop', 'Disney Pop', NOW()),
  (gen_random_uuid(), 'diva house', 'Diva House', NOW()),
  (gen_random_uuid(), 'divine rock', 'Divine Rock', NOW()),
  (gen_random_uuid(), 'dixieland', 'Dixieland', NOW()),
  (gen_random_uuid(), 'dixieland jazz', 'Dixieland Jazz', NOW()),
  (gen_random_uuid(), 'djambadon', 'Djambadon', NOW()),
  (gen_random_uuid(), 'djent', 'Djent', NOW()),
  (gen_random_uuid(), 'dodompa', 'Dodompa', NOW()),
  (gen_random_uuid(), 'doina', 'Doina', NOW()),
  (gen_random_uuid(), 'dombola', 'Dombola', NOW()),
  (gen_random_uuid(), 'dondang sayang', 'Dondang Sayang', NOW()),
  (gen_random_uuid(), 'donegal fiddle tradition', 'Donegal Fiddle Tradition', NOW()),
  (gen_random_uuid(), 'dongjing', 'Dongjing', NOW()),
  (gen_random_uuid(), 'doo wop', 'Doo Wop', NOW()),
  (gen_random_uuid(), 'doom metal', 'Doom Metal', NOW()),
  (gen_random_uuid(), 'doomcore', 'Doomcore', NOW()),
  (gen_random_uuid(), 'downtempo', 'Downtempo', NOW()),
  (gen_random_uuid(), 'drag', 'Drag', NOW()),
  (gen_random_uuid(), 'dream pop', 'Dream Pop', NOW()),
  (gen_random_uuid(), 'drone doom', 'Drone Doom', NOW()),
  (gen_random_uuid(), 'drone metal', 'Drone Metal', NOW()),
  (gen_random_uuid(), 'drone music', 'Drone Music', NOW()),
  (gen_random_uuid(), 'dronology', 'Dronology', NOW()),
  (gen_random_uuid(), 'drum and bass', 'Drum And Bass', NOW()),
  (gen_random_uuid(), 'dub', 'Dub', NOW()),
  (gen_random_uuid(), 'dub house', 'Dub House', NOW()),
  (gen_random_uuid(), 'dubanguthu', 'Dubanguthu', NOW()),
  (gen_random_uuid(), 'dubstep', 'Dubstep', NOW()),
  (gen_random_uuid(), 'dubtronica', 'Dubtronica', NOW()),
  (gen_random_uuid(), 'dunedin sound', 'Dunedin Sound', NOW()),
  (gen_random_uuid(), 'dunun', 'Dunun', NOW()),
  (gen_random_uuid(), 'dutch jazz', 'Dutch Jazz', NOW()),
  (gen_random_uuid(), 'décima', 'Décima', NOW()),
  (gen_random_uuid(), 'early music', 'Early Music', NOW()),
  (gen_random_uuid(), 'east coast blues', 'East Coast Blues', NOW()),
  (gen_random_uuid(), 'east coast hip hop', 'East Coast Hip Hop', NOW()),
  (gen_random_uuid(), 'easy listening', 'Easy Listening', NOW()),
  (gen_random_uuid(), 'electric blues', 'Electric Blues', NOW()),
  (gen_random_uuid(), 'electric folk', 'Electric Folk', NOW()),
  (gen_random_uuid(), 'electro', 'Electro', NOW()),
  (gen_random_uuid(), 'electro backbeat', 'Electro Backbeat', NOW()),
  (gen_random_uuid(), 'electro hop', 'Electro Hop', NOW()),
  (gen_random_uuid(), 'electro house', 'Electro House', NOW()),
  (gen_random_uuid(), 'electro punk', 'Electro Punk', NOW()),
  (gen_random_uuid(), 'electro-industrial', 'Electro-industrial', NOW()),
  (gen_random_uuid(), 'electro-swing', 'Electro-swing', NOW()),
  (gen_random_uuid(), 'electroclash', 'Electroclash', NOW()),
  (gen_random_uuid(), 'electrofunk', 'Electrofunk', NOW()),
  (gen_random_uuid(), 'electronic', 'Electronic', NOW()),
  (gen_random_uuid(), 'electronic art music', 'Electronic Art Music', NOW()),
  (gen_random_uuid(), 'electronic body music', 'Electronic Body Music', NOW()),
  (gen_random_uuid(), 'electronic dance', 'Electronic Dance', NOW()),
  (gen_random_uuid(), 'electronic luk thung', 'Electronic Luk Thung', NOW()),
  (gen_random_uuid(), 'electronic music', 'Electronic Music', NOW()),
  (gen_random_uuid(), 'electronic rock', 'Electronic Rock', NOW()),
  (gen_random_uuid(), 'electronica', 'Electronica', NOW()),
  (gen_random_uuid(), 'electropop', 'Electropop', NOW()),
  (gen_random_uuid(), 'elevator music', 'Elevator Music', NOW()),
  (gen_random_uuid(), 'emo', 'Emo', NOW()),
  (gen_random_uuid(), 'emo pop', 'Emo Pop', NOW()),
  (gen_random_uuid(), 'emo rap', 'Emo Rap', NOW()),
  (gen_random_uuid(), 'emocore', 'Emocore', NOW()),
  (gen_random_uuid(), 'emotronic', 'Emotronic', NOW()),
  (gen_random_uuid(), 'enka', 'Enka', NOW()),
  (gen_random_uuid(), 'epic doom metal', 'Epic Doom Metal', NOW()),
  (gen_random_uuid(), 'epic metal', 'Epic Metal', NOW()),
  (gen_random_uuid(), 'eremwu eu', 'Eremwu Eu', NOW()),
  (gen_random_uuid(), 'ethereal pop', 'Ethereal Pop', NOW()),
  (gen_random_uuid(), 'ethereal wave', 'Ethereal Wave', NOW()),
  (gen_random_uuid(), 'euro', 'Euro', NOW()),
  (gen_random_uuid(), 'euro disco', 'Euro Disco', NOW()),
  (gen_random_uuid(), 'eurobeat', 'Eurobeat', NOW()),
  (gen_random_uuid(), 'eurodance', 'Eurodance', NOW()),
  (gen_random_uuid(), 'europop', 'Europop', NOW()),
  (gen_random_uuid(), 'eurotrance', 'Eurotrance', NOW()),
  (gen_random_uuid(), 'eurourban', 'Eurourban', NOW()),
  (gen_random_uuid(), 'exotica', 'Exotica', NOW()),
  (gen_random_uuid(), 'experimental music', 'Experimental Music', NOW()),
  (gen_random_uuid(), 'experimental noise', 'Experimental Noise', NOW()),
  (gen_random_uuid(), 'experimental pop', 'Experimental Pop', NOW()),
  (gen_random_uuid(), 'experimental rock', 'Experimental Rock', NOW()),
  (gen_random_uuid(), 'extreme metal', 'Extreme Metal', NOW()),
  (gen_random_uuid(), 'ezengileer', 'Ezengileer', NOW()),
  (gen_random_uuid(), 'fado', 'Fado', NOW()),
  (gen_random_uuid(), 'falak', 'Falak', NOW()),
  (gen_random_uuid(), 'fandango', 'Fandango', NOW()),
  (gen_random_uuid(), 'farruca', 'Farruca', NOW()),
  (gen_random_uuid(), 'fife and drum blues', 'Fife And Drum Blues', NOW()),
  (gen_random_uuid(), 'filk', 'Filk', NOW()),
  (gen_random_uuid(), 'film score', 'Film Score', NOW()),
  (gen_random_uuid(), 'filmi', 'Filmi', NOW()),
  (gen_random_uuid(), 'filmi-ghazal', 'Filmi-ghazal', NOW()),
  (gen_random_uuid(), 'finger-style', 'Finger-style', NOW()),
  (gen_random_uuid(), 'fjatpangarri', 'Fjatpangarri', NOW()),
  (gen_random_uuid(), 'flamenco', 'Flamenco', NOW()),
  (gen_random_uuid(), 'flamenco rumba', 'Flamenco Rumba', NOW()),
  (gen_random_uuid(), 'flower power', 'Flower Power', NOW()),
  (gen_random_uuid(), 'foaie verde', 'Foaie Verde', NOW()),
  (gen_random_uuid(), 'fofa', 'Fofa', NOW()),
  (gen_random_uuid(), 'folk hop', 'Folk Hop', NOW()),
  (gen_random_uuid(), 'folk metal', 'Folk Metal', NOW()),
  (gen_random_uuid(), 'folk music', 'Folk Music', NOW()),
  (gen_random_uuid(), 'folk pop', 'Folk Pop', NOW()),
  (gen_random_uuid(), 'folk punk', 'Folk Punk', NOW()),
  (gen_random_uuid(), 'folk rock', 'Folk Rock', NOW()),
  (gen_random_uuid(), 'folktronica', 'Folktronica', NOW()),
  (gen_random_uuid(), 'forró', 'Forró', NOW()),
  (gen_random_uuid(), 'franco-country', 'Franco-country', NOW()),
  (gen_random_uuid(), 'freak-folk', 'Freak-folk', NOW()),
  (gen_random_uuid(), 'freakbeat', 'Freakbeat', NOW()),
  (gen_random_uuid(), 'free improvisation', 'Free Improvisation', NOW()),
  (gen_random_uuid(), 'free jazz', 'Free Jazz', NOW()),
  (gen_random_uuid(), 'free music', 'Free Music', NOW()),
  (gen_random_uuid(), 'freestyle', 'Freestyle', NOW()),
  (gen_random_uuid(), 'freestyle house', 'Freestyle House', NOW()),
  (gen_random_uuid(), 'freetekno', 'Freetekno', NOW()),
  (gen_random_uuid(), 'french pop', 'French Pop', NOW()),
  (gen_random_uuid(), 'frenchcore', 'Frenchcore', NOW()),
  (gen_random_uuid(), 'frevo', 'Frevo', NOW()),
  (gen_random_uuid(), 'fricote', 'Fricote', NOW()),
  (gen_random_uuid(), 'fuji', 'Fuji', NOW()),
  (gen_random_uuid(), 'fuji music', 'Fuji Music', NOW()),
  (gen_random_uuid(), 'fulia', 'Fulia', NOW()),
  (gen_random_uuid(), 'full on', 'Full On', NOW()),
  (gen_random_uuid(), 'funaná', 'Funaná', NOW()),
  (gen_random_uuid(), 'funeral doom', 'Funeral Doom', NOW()),
  (gen_random_uuid(), 'funk', 'Funk', NOW()),
  (gen_random_uuid(), 'funk metal', 'Funk Metal', NOW()),
  (gen_random_uuid(), 'funk rock', 'Funk Rock', NOW()),
  (gen_random_uuid(), 'funkcore', 'Funkcore', NOW()),
  (gen_random_uuid(), 'funky house', 'Funky House', NOW()),
  (gen_random_uuid(), 'furniture music', 'Furniture Music', NOW()),
  (gen_random_uuid(), 'fusion jazz', 'Fusion Jazz', NOW()),
  (gen_random_uuid(), 'g-funk', 'G-funk', NOW()),
  (gen_random_uuid(), 'gaana', 'Gaana', NOW()),
  (gen_random_uuid(), 'gabba', 'Gabba', NOW()),
  (gen_random_uuid(), 'gabber', 'Gabber', NOW()),
  (gen_random_uuid(), 'gagaku', 'Gagaku', NOW()),
  (gen_random_uuid(), 'gaikyoku', 'Gaikyoku', NOW()),
  (gen_random_uuid(), 'gaita', 'Gaita', NOW()),
  (gen_random_uuid(), 'galant', 'Galant', NOW()),
  (gen_random_uuid(), 'gamad', 'Gamad', NOW()),
  (gen_random_uuid(), 'gambang kromong', 'Gambang Kromong', NOW()),
  (gen_random_uuid(), 'gamelan', 'Gamelan', NOW()),
  (gen_random_uuid(), 'gamelan angklung', 'Gamelan Angklung', NOW()),
  (gen_random_uuid(), 'gamelan bang', 'Gamelan Bang', NOW()),
  (gen_random_uuid(), 'gamelan bebonangan', 'Gamelan Bebonangan', NOW()),
  (gen_random_uuid(), 'gamelan buh', 'Gamelan Buh', NOW()),
  (gen_random_uuid(), 'gamelan degung', 'Gamelan Degung', NOW()),
  (gen_random_uuid(), 'gamelan gede', 'Gamelan Gede', NOW()),
  (gen_random_uuid(), 'gamelan kebyar', 'Gamelan Kebyar', NOW()),
  (gen_random_uuid(), 'gamelan salendro', 'Gamelan Salendro', NOW()),
  (gen_random_uuid(), 'gamelan selunding', 'Gamelan Selunding', NOW()),
  (gen_random_uuid(), 'gamelan semar pegulingan', 'Gamelan Semar Pegulingan', NOW()),
  (gen_random_uuid(), 'gamewave', 'Gamewave', NOW()),
  (gen_random_uuid(), 'gammeldans', 'Gammeldans', NOW()),
  (gen_random_uuid(), 'gandrung', 'Gandrung', NOW()),
  (gen_random_uuid(), 'gangsta rap', 'Gangsta Rap', NOW()),
  (gen_random_uuid(), 'gar', 'Gar', NOW()),
  (gen_random_uuid(), 'garage rock', 'Garage Rock', NOW()),
  (gen_random_uuid(), 'garrotin', 'Garrotin', NOW()),
  (gen_random_uuid(), 'gavotte', 'Gavotte', NOW()),
  (gen_random_uuid(), 'gelugpa chanting', 'Gelugpa Chanting', NOW()),
  (gen_random_uuid(), 'gender wayang', 'Gender Wayang', NOW()),
  (gen_random_uuid(), 'gending', 'Gending', NOW()),
  (gen_random_uuid(), 'german folk music', 'German Folk Music', NOW()),
  (gen_random_uuid(), 'gharbi', 'Gharbi', NOW()),
  (gen_random_uuid(), 'gharnati', 'Gharnati', NOW()),
  (gen_random_uuid(), 'ghazal', 'Ghazal', NOW()),
  (gen_random_uuid(), 'ghazal-song', 'Ghazal-song', NOW()),
  (gen_random_uuid(), 'ghetto house', 'Ghetto House', NOW()),
  (gen_random_uuid(), 'ghettotech', 'Ghettotech', NOW()),
  (gen_random_uuid(), 'girl group', 'Girl Group', NOW()),
  (gen_random_uuid(), 'glam metal', 'Glam Metal', NOW()),
  (gen_random_uuid(), 'glam punk', 'Glam Punk', NOW()),
  (gen_random_uuid(), 'glam rock', 'Glam Rock', NOW()),
  (gen_random_uuid(), 'glitch', 'Glitch', NOW()),
  (gen_random_uuid(), 'gnawa', 'Gnawa', NOW()),
  (gen_random_uuid(), 'go-go', 'Go-go', NOW()),
  (gen_random_uuid(), 'goa', 'Goa', NOW()),
  (gen_random_uuid(), 'goa trance', 'Goa Trance', NOW()),
  (gen_random_uuid(), 'gong-chime music', 'Gong-chime Music', NOW()),
  (gen_random_uuid(), 'goombay', 'Goombay', NOW()),
  (gen_random_uuid(), 'goregrind', 'Goregrind', NOW()),
  (gen_random_uuid(), 'goshu ondo', 'Goshu Ondo', NOW()),
  (gen_random_uuid(), 'gospel music', 'Gospel Music', NOW()),
  (gen_random_uuid(), 'gothic metal', 'Gothic Metal', NOW()),
  (gen_random_uuid(), 'gothic rock', 'Gothic Rock', NOW()),
  (gen_random_uuid(), 'granadinas', 'Granadinas', NOW()),
  (gen_random_uuid(), 'grebo', 'Grebo', NOW()),
  (gen_random_uuid(), 'gregorian chant', 'Gregorian Chant', NOW()),
  (gen_random_uuid(), 'grime', 'Grime', NOW()),
  (gen_random_uuid(), 'grindcore', 'Grindcore', NOW()),
  (gen_random_uuid(), 'groove metal', 'Groove Metal', NOW()),
  (gen_random_uuid(), 'group sounds', 'Group Sounds', NOW()),
  (gen_random_uuid(), 'grunge', 'Grunge', NOW()),
  (gen_random_uuid(), 'grupera', 'Grupera', NOW()),
  (gen_random_uuid(), 'guaguanbo', 'Guaguanbo', NOW()),
  (gen_random_uuid(), 'guajira', 'Guajira', NOW()),
  (gen_random_uuid(), 'guasca', 'Guasca', NOW()),
  (gen_random_uuid(), 'guitarra baiana', 'Guitarra Baiana', NOW()),
  (gen_random_uuid(), 'guitarradas', 'Guitarradas', NOW()),
  (gen_random_uuid(), 'gumbe', 'Gumbe', NOW()),
  (gen_random_uuid(), 'gunchei', 'Gunchei', NOW()),
  (gen_random_uuid(), 'gunka', 'Gunka', NOW()),
  (gen_random_uuid(), 'guoyue', 'Guoyue', NOW()),
  (gen_random_uuid(), 'gwo ka', 'Gwo Ka', NOW()),
  (gen_random_uuid(), 'gwo ka moderne', 'Gwo Ka Moderne', NOW()),
  (gen_random_uuid(), 'gypsy jazz', 'Gypsy Jazz', NOW()),
  (gen_random_uuid(), 'gypsy punk', 'Gypsy Punk', NOW()),
  (gen_random_uuid(), 'gypsybilly', 'Gypsybilly', NOW()),
  (gen_random_uuid(), 'gyu ke', 'Gyu Ke', NOW()),
  (gen_random_uuid(), 'habanera', 'Habanera', NOW()),
  (gen_random_uuid(), 'hajnali', 'Hajnali', NOW()),
  (gen_random_uuid(), 'hakka', 'Hakka', NOW()),
  (gen_random_uuid(), 'halling', 'Halling', NOW()),
  (gen_random_uuid(), 'hambo', 'Hambo', NOW()),
  (gen_random_uuid(), 'hands up', 'Hands Up', NOW()),
  (gen_random_uuid(), 'hapa haole', 'Hapa Haole', NOW()),
  (gen_random_uuid(), 'happy hardcore', 'Happy Hardcore', NOW()),
  (gen_random_uuid(), 'haqibah', 'Haqibah', NOW()),
  (gen_random_uuid(), 'hard', 'Hard', NOW()),
  (gen_random_uuid(), 'hard bop', 'Hard Bop', NOW()),
  (gen_random_uuid(), 'hard house', 'Hard House', NOW()),
  (gen_random_uuid(), 'hard rock', 'Hard Rock', NOW()),
  (gen_random_uuid(), 'hard trance', 'Hard Trance', NOW()),
  (gen_random_uuid(), 'hardcore hip hop', 'Hardcore Hip Hop', NOW()),
  (gen_random_uuid(), 'hardcore metal', 'Hardcore Metal', NOW()),
  (gen_random_uuid(), 'hardcore punk', 'Hardcore Punk', NOW()),
  (gen_random_uuid(), 'hardcore techno', 'Hardcore Techno', NOW()),
  (gen_random_uuid(), 'hardstyle', 'Hardstyle', NOW()),
  (gen_random_uuid(), 'harepa', 'Harepa', NOW()),
  (gen_random_uuid(), 'harmonica blues', 'Harmonica Blues', NOW()),
  (gen_random_uuid(), 'hasaposérviko', 'Hasaposérviko', NOW()),
  (gen_random_uuid(), 'heart attack', 'Heart Attack', NOW()),
  (gen_random_uuid(), 'heartland rock', 'Heartland Rock', NOW()),
  (gen_random_uuid(), 'heavy beat', 'Heavy Beat', NOW()),
  (gen_random_uuid(), 'heavy metal', 'Heavy Metal', NOW()),
  (gen_random_uuid(), 'hesher', 'Hesher', NOW()),
  (gen_random_uuid(), 'hi-nrg', 'Hi-nrg', NOW()),
  (gen_random_uuid(), 'highlands', 'Highlands', NOW()),
  (gen_random_uuid(), 'highlife', 'Highlife', NOW()),
  (gen_random_uuid(), 'highlife fusion', 'Highlife Fusion', NOW()),
  (gen_random_uuid(), 'hillybilly music', 'Hillybilly Music', NOW()),
  (gen_random_uuid(), 'hindustani classical music', 'Hindustani Classical Music', NOW()),
  (gen_random_uuid(), 'hip hop', 'Hip Hop', NOW()),
  (gen_random_uuid(), 'hip hop & rap', 'Hip Hop & Rap', NOW()),
  (gen_random_uuid(), 'hip hop soul', 'Hip Hop Soul', NOW()),
  (gen_random_uuid(), 'hip house', 'Hip House', NOW()),
  (gen_random_uuid(), 'hiplife', 'Hiplife', NOW()),
  (gen_random_uuid(), 'hiragasy', 'Hiragasy', NOW()),
  (gen_random_uuid(), 'hiva usu', 'Hiva Usu', NOW()),
  (gen_random_uuid(), 'hong kong and cantonese pop', 'Hong Kong And Cantonese Pop', NOW()),
  (gen_random_uuid(), 'hong kong english pop', 'Hong Kong English Pop', NOW()),
  (gen_random_uuid(), 'honky tonk', 'Honky Tonk', NOW()),
  (gen_random_uuid(), 'honkyoku', 'Honkyoku', NOW()),
  (gen_random_uuid(), 'hora lunga', 'Hora Lunga', NOW()),
  (gen_random_uuid(), 'hornpipe', 'Hornpipe', NOW()),
  (gen_random_uuid(), 'horror punk', 'Horror Punk', NOW()),
  (gen_random_uuid(), 'horrorcore', 'Horrorcore', NOW()),
  (gen_random_uuid(), 'horrorcore rap', 'Horrorcore Rap', NOW()),
  (gen_random_uuid(), 'house', 'House', NOW()),
  (gen_random_uuid(), 'house music', 'House Music', NOW()),
  (gen_random_uuid(), 'hua''er', 'Hua''er', NOW()),
  (gen_random_uuid(), 'huasteco', 'Huasteco', NOW()),
  (gen_random_uuid(), 'huayno', 'Huayno', NOW()),
  (gen_random_uuid(), 'hula', 'Hula', NOW()),
  (gen_random_uuid(), 'humor', 'Humor', NOW()),
  (gen_random_uuid(), 'humppa', 'Humppa', NOW()),
  (gen_random_uuid(), 'hunguhungu', 'Hunguhungu', NOW()),
  (gen_random_uuid(), 'hyangak', 'Hyangak', NOW()),
  (gen_random_uuid(), 'hymn', 'Hymn', NOW()),
  (gen_random_uuid(), 'hyphy', 'Hyphy', NOW()),
  (gen_random_uuid(), 'hát chau van', 'Hát Chau Van', NOW()),
  (gen_random_uuid(), 'hát chèo', 'Hát Chèo', NOW()),
  (gen_random_uuid(), 'hát cãi luong', 'Hát Cãi Luong', NOW()),
  (gen_random_uuid(), 'hát tuồng', 'Hát Tuồng', NOW()),
  (gen_random_uuid(), 'ibiza music', 'Ibiza Music', NOW()),
  (gen_random_uuid(), 'icaro', 'Icaro', NOW()),
  (gen_random_uuid(), 'idm', 'Idm', NOW()),
  (gen_random_uuid(), 'igbo music', 'Igbo Music', NOW()),
  (gen_random_uuid(), 'ijexá', 'Ijexá', NOW()),
  (gen_random_uuid(), 'ilahije', 'Ilahije', NOW()),
  (gen_random_uuid(), 'illbient', 'Illbient', NOW()),
  (gen_random_uuid(), 'impressionist music', 'Impressionist Music', NOW()),
  (gen_random_uuid(), 'improvisational', 'Improvisational', NOW()),
  (gen_random_uuid(), 'incidental music', 'Incidental Music', NOW()),
  (gen_random_uuid(), 'indian pop', 'Indian Pop', NOW()),
  (gen_random_uuid(), 'indie folk', 'Indie Folk', NOW()),
  (gen_random_uuid(), 'indie music', 'Indie Music', NOW()),
  (gen_random_uuid(), 'indie pop', 'Indie Pop', NOW()),
  (gen_random_uuid(), 'indie rock', 'Indie Rock', NOW()),
  (gen_random_uuid(), 'indietronica', 'Indietronica', NOW()),
  (gen_random_uuid(), 'indo jazz', 'Indo Jazz', NOW()),
  (gen_random_uuid(), 'indo rock', 'Indo Rock', NOW()),
  (gen_random_uuid(), 'indonesian pop', 'Indonesian Pop', NOW()),
  (gen_random_uuid(), 'indoyíftika', 'Indoyíftika', NOW()),
  (gen_random_uuid(), 'industrial death metal', 'Industrial Death Metal', NOW()),
  (gen_random_uuid(), 'industrial hip hop', 'Industrial Hip Hop', NOW()),
  (gen_random_uuid(), 'industrial metal', 'Industrial Metal', NOW()),
  (gen_random_uuid(), 'industrial music', 'Industrial Music', NOW()),
  (gen_random_uuid(), 'industrial musical', 'Industrial Musical', NOW()),
  (gen_random_uuid(), 'industrial rock', 'Industrial Rock', NOW()),
  (gen_random_uuid(), 'instrumental rock', 'Instrumental Rock', NOW()),
  (gen_random_uuid(), 'intelligent dance music', 'Intelligent Dance Music', NOW()),
  (gen_random_uuid(), 'international latin', 'International Latin', NOW()),
  (gen_random_uuid(), 'inuit music', 'Inuit Music', NOW()),
  (gen_random_uuid(), 'iranian pop', 'Iranian Pop', NOW()),
  (gen_random_uuid(), 'irish folk', 'Irish Folk', NOW()),
  (gen_random_uuid(), 'irish rebel music', 'Irish Rebel Music', NOW()),
  (gen_random_uuid(), 'iscathamiya', 'Iscathamiya', NOW()),
  (gen_random_uuid(), 'isicathamiya', 'Isicathamiya', NOW()),
  (gen_random_uuid(), 'isikhwela jo', 'Isikhwela Jo', NOW()),
  (gen_random_uuid(), 'island', 'Island', NOW()),
  (gen_random_uuid(), 'isolationist', 'Isolationist', NOW()),
  (gen_random_uuid(), 'italo dance', 'Italo Dance', NOW()),
  (gen_random_uuid(), 'italo disco', 'Italo Disco', NOW()),
  (gen_random_uuid(), 'italo house', 'Italo House', NOW()),
  (gen_random_uuid(), 'itsmeños', 'Itsmeños', NOW()),
  (gen_random_uuid(), 'izvorna bosanska muzika', 'Izvorna Bosanska Muzika', NOW()),
  (gen_random_uuid(), 'j''ouvert', 'J''ouvert', NOW()),
  (gen_random_uuid(), 'j-fusion', 'J-fusion', NOW()),
  (gen_random_uuid(), 'j-pop', 'J-pop', NOW()),
  (gen_random_uuid(), 'j-rock', 'J-rock', NOW()),
  (gen_random_uuid(), 'jaipongan', 'Jaipongan', NOW()),
  (gen_random_uuid(), 'jaliscienses', 'Jaliscienses', NOW()),
  (gen_random_uuid(), 'jam band', 'Jam Band', NOW()),
  (gen_random_uuid(), 'jam rock', 'Jam Rock', NOW()),
  (gen_random_uuid(), 'jamana kura', 'Jamana Kura', NOW()),
  (gen_random_uuid(), 'jamrieng samai', 'Jamrieng Samai', NOW()),
  (gen_random_uuid(), 'jangle pop', 'Jangle Pop', NOW()),
  (gen_random_uuid(), 'japanese pop', 'Japanese Pop', NOW()),
  (gen_random_uuid(), 'jarana', 'Jarana', NOW()),
  (gen_random_uuid(), 'jariang', 'Jariang', NOW()),
  (gen_random_uuid(), 'jarochos', 'Jarochos', NOW()),
  (gen_random_uuid(), 'jawaiian', 'Jawaiian', NOW()),
  (gen_random_uuid(), 'jazz', 'Jazz', NOW()),
  (gen_random_uuid(), 'jazz blues', 'Jazz Blues', NOW()),
  (gen_random_uuid(), 'jazz fusion', 'Jazz Fusion', NOW()),
  (gen_random_uuid(), 'jazz metal', 'Jazz Metal', NOW()),
  (gen_random_uuid(), 'jazz rap', 'Jazz Rap', NOW()),
  (gen_random_uuid(), 'jazz-funk', 'Jazz-funk', NOW()),
  (gen_random_uuid(), 'jazz-rock', 'Jazz-rock', NOW()),
  (gen_random_uuid(), 'jegog', 'Jegog', NOW()),
  (gen_random_uuid(), 'jenkka', 'Jenkka', NOW()),
  (gen_random_uuid(), 'jesus music', 'Jesus Music', NOW()),
  (gen_random_uuid(), 'jibaro', 'Jibaro', NOW()),
  (gen_random_uuid(), 'jig', 'Jig', NOW()),
  (gen_random_uuid(), 'jig punk', 'Jig Punk', NOW()),
  (gen_random_uuid(), 'jing ping', 'Jing Ping', NOW()),
  (gen_random_uuid(), 'jingle', 'Jingle', NOW()),
  (gen_random_uuid(), 'jit', 'Jit', NOW()),
  (gen_random_uuid(), 'jitterbug', 'Jitterbug', NOW()),
  (gen_random_uuid(), 'jive', 'Jive', NOW()),
  (gen_random_uuid(), 'joged', 'Joged', NOW()),
  (gen_random_uuid(), 'joged bumbung', 'Joged Bumbung', NOW()),
  (gen_random_uuid(), 'joik', 'Joik', NOW()),
  (gen_random_uuid(), 'jonnycore', 'Jonnycore', NOW()),
  (gen_random_uuid(), 'joropo', 'Joropo', NOW()),
  (gen_random_uuid(), 'jota', 'Jota', NOW()),
  (gen_random_uuid(), 'jtek', 'Jtek', NOW()),
  (gen_random_uuid(), 'jug band', 'Jug Band', NOW()),
  (gen_random_uuid(), 'jujitsu', 'Jujitsu', NOW()),
  (gen_random_uuid(), 'juju', 'Juju', NOW()),
  (gen_random_uuid(), 'juke joint blues', 'Juke Joint Blues', NOW()),
  (gen_random_uuid(), 'jump blues', 'Jump Blues', NOW()),
  (gen_random_uuid(), 'jumpstyle', 'Jumpstyle', NOW()),
  (gen_random_uuid(), 'jungle', 'Jungle', NOW()),
  (gen_random_uuid(), 'junkanoo', 'Junkanoo', NOW()),
  (gen_random_uuid(), 'juré', 'Juré', NOW()),
  (gen_random_uuid(), 'jùjú', 'Jùjú', NOW()),
  (gen_random_uuid(), 'k-pop', 'K-pop', NOW()),
  (gen_random_uuid(), 'kaba', 'Kaba', NOW()),
  (gen_random_uuid(), 'kabuki', 'Kabuki', NOW()),
  (gen_random_uuid(), 'kachāshī', 'Kachāshī', NOW()),
  (gen_random_uuid(), 'kadans', 'Kadans', NOW()),
  (gen_random_uuid(), 'kagok', 'Kagok', NOW()),
  (gen_random_uuid(), 'kagyupa chanting', 'Kagyupa Chanting', NOW()),
  (gen_random_uuid(), 'kaiso', 'Kaiso', NOW()),
  (gen_random_uuid(), 'kalamatianó', 'Kalamatianó', NOW()),
  (gen_random_uuid(), 'kalattuut', 'Kalattuut', NOW()),
  (gen_random_uuid(), 'kalinda', 'Kalinda', NOW()),
  (gen_random_uuid(), 'kamba pop', 'Kamba Pop', NOW()),
  (gen_random_uuid(), 'kan ha diskan', 'Kan Ha Diskan', NOW()),
  (gen_random_uuid(), 'kansas city blues', 'Kansas City Blues', NOW()),
  (gen_random_uuid(), 'kantrum', 'Kantrum', NOW()),
  (gen_random_uuid(), 'kantádhes', 'Kantádhes', NOW()),
  (gen_random_uuid(), 'kargyraa', 'Kargyraa', NOW()),
  (gen_random_uuid(), 'karma', 'Karma', NOW()),
  (gen_random_uuid(), 'kaseko', 'Kaseko', NOW()),
  (gen_random_uuid(), 'katajjaq', 'Katajjaq', NOW()),
  (gen_random_uuid(), 'kawachi ondo', 'Kawachi Ondo', NOW()),
  (gen_random_uuid(), 'kayōkyoku', 'Kayōkyoku', NOW()),
  (gen_random_uuid(), 'ke-kwe', 'Ke-kwe', NOW()),
  (gen_random_uuid(), 'kebyar', 'Kebyar', NOW()),
  (gen_random_uuid(), 'kecak', 'Kecak', NOW()),
  (gen_random_uuid(), 'kecapi suling', 'Kecapi Suling', NOW()),
  (gen_random_uuid(), 'kertok', 'Kertok', NOW()),
  (gen_random_uuid(), 'khaleeji', 'Khaleeji', NOW()),
  (gen_random_uuid(), 'khap', 'Khap', NOW()),
  (gen_random_uuid(), 'khelimaski djili', 'Khelimaski Djili', NOW()),
  (gen_random_uuid(), 'khene', 'Khene', NOW()),
  (gen_random_uuid(), 'khoomei', 'Khoomei', NOW()),
  (gen_random_uuid(), 'khorovodi', 'Khorovodi', NOW()),
  (gen_random_uuid(), 'khplam wai', 'Khplam Wai', NOW()),
  (gen_random_uuid(), 'khrung sai', 'Khrung Sai', NOW()),
  (gen_random_uuid(), 'khyal', 'Khyal', NOW()),
  (gen_random_uuid(), 'kilapanda', 'Kilapanda', NOW()),
  (gen_random_uuid(), 'kinko', 'Kinko', NOW()),
  (gen_random_uuid(), 'kirtan', 'Kirtan', NOW()),
  (gen_random_uuid(), 'kiwi rock', 'Kiwi Rock', NOW()),
  (gen_random_uuid(), 'kizomba', 'Kizomba', NOW()),
  (gen_random_uuid(), 'klape', 'Klape', NOW()),
  (gen_random_uuid(), 'klasik', 'Klasik', NOW()),
  (gen_random_uuid(), 'klezmer', 'Klezmer', NOW()),
  (gen_random_uuid(), 'kliningan', 'Kliningan', NOW()),
  (gen_random_uuid(), 'kléftiko', 'Kléftiko', NOW()),
  (gen_random_uuid(), 'kochare', 'Kochare', NOW()),
  (gen_random_uuid(), 'kolomyjka', 'Kolomyjka', NOW()),
  (gen_random_uuid(), 'komagaku', 'Komagaku', NOW()),
  (gen_random_uuid(), 'kompa', 'Kompa', NOW()),
  (gen_random_uuid(), 'konpa', 'Konpa', NOW()),
  (gen_random_uuid(), 'korean pop', 'Korean Pop', NOW()),
  (gen_random_uuid(), 'koumpaneia', 'Koumpaneia', NOW()),
  (gen_random_uuid(), 'kpanlogo', 'Kpanlogo', NOW()),
  (gen_random_uuid(), 'krakowiak', 'Krakowiak', NOW()),
  (gen_random_uuid(), 'krautrock', 'Krautrock', NOW()),
  (gen_random_uuid(), 'kriti', 'Kriti', NOW()),
  (gen_random_uuid(), 'kroncong', 'Kroncong', NOW()),
  (gen_random_uuid(), 'krump', 'Krump', NOW()),
  (gen_random_uuid(), 'krzesany', 'Krzesany', NOW()),
  (gen_random_uuid(), 'kuduro', 'Kuduro', NOW()),
  (gen_random_uuid(), 'kulintang', 'Kulintang', NOW()),
  (gen_random_uuid(), 'kulning', 'Kulning', NOW()),
  (gen_random_uuid(), 'kumina', 'Kumina', NOW()),
  (gen_random_uuid(), 'kun-borrk', 'Kun-borrk', NOW()),
  (gen_random_uuid(), 'kundere', 'Kundere', NOW()),
  (gen_random_uuid(), 'kundiman', 'Kundiman', NOW()),
  (gen_random_uuid(), 'kussundé', 'Kussundé', NOW()),
  (gen_random_uuid(), 'kutumba wake', 'Kutumba Wake', NOW()),
  (gen_random_uuid(), 'kveding', 'Kveding', NOW()),
  (gen_random_uuid(), 'kvæði', 'Kvæði', NOW()),
  (gen_random_uuid(), 'kwaito', 'Kwaito', NOW()),
  (gen_random_uuid(), 'kwassa kwassa', 'Kwassa Kwassa', NOW()),
  (gen_random_uuid(), 'kwela', 'Kwela', NOW()),
  (gen_random_uuid(), 'käng', 'Käng', NOW()),
  (gen_random_uuid(), 'kélé', 'Kélé', NOW()),
  (gen_random_uuid(), 'kĩkũyũ pop', 'Kĩkũyũ Pop', NOW()),
  (gen_random_uuid(), 'la la', 'La La', NOW()),
  (gen_random_uuid(), 'latin american', 'Latin American', NOW()),
  (gen_random_uuid(), 'latin jazz', 'Latin Jazz', NOW()),
  (gen_random_uuid(), 'latin pop', 'Latin Pop', NOW()),
  (gen_random_uuid(), 'latin rap', 'Latin Rap', NOW()),
  (gen_random_uuid(), 'lavway', 'Lavway', NOW()),
  (gen_random_uuid(), 'laïko', 'Laïko', NOW()),
  (gen_random_uuid(), 'laïkó', 'Laïkó', NOW()),
  (gen_random_uuid(), 'le leagan', 'Le Leagan', NOW()),
  (gen_random_uuid(), 'legényes', 'Legényes', NOW()),
  (gen_random_uuid(), 'lelio', 'Lelio', NOW()),
  (gen_random_uuid(), 'letkajenkka', 'Letkajenkka', NOW()),
  (gen_random_uuid(), 'levenslied', 'Levenslied', NOW()),
  (gen_random_uuid(), 'lhamo', 'Lhamo', NOW()),
  (gen_random_uuid(), 'lieder', 'Lieder', NOW()),
  (gen_random_uuid(), 'light music', 'Light Music', NOW()),
  (gen_random_uuid(), 'light rock', 'Light Rock', NOW()),
  (gen_random_uuid(), 'likanos', 'Likanos', NOW()),
  (gen_random_uuid(), 'liquid drum&bass', 'Liquid Drum&bass', NOW()),
  (gen_random_uuid(), 'liquid funk', 'Liquid Funk', NOW()),
  (gen_random_uuid(), 'liquindi', 'Liquindi', NOW()),
  (gen_random_uuid(), 'llanera', 'Llanera', NOW()),
  (gen_random_uuid(), 'llanto', 'Llanto', NOW()),
  (gen_random_uuid(), 'lo-fi', 'Lo-fi', NOW()),
  (gen_random_uuid(), 'lo-fi music', 'Lo-fi Music', NOW()),
  (gen_random_uuid(), 'loki djili', 'Loki Djili', NOW()),
  (gen_random_uuid(), 'long-song', 'Long-song', NOW()),
  (gen_random_uuid(), 'louisiana blues', 'Louisiana Blues', NOW()),
  (gen_random_uuid(), 'louisiana swamp pop', 'Louisiana Swamp Pop', NOW()),
  (gen_random_uuid(), 'lounge music', 'Lounge Music', NOW()),
  (gen_random_uuid(), 'lovers rock', 'Lovers Rock', NOW()),
  (gen_random_uuid(), 'lowercase', 'Lowercase', NOW()),
  (gen_random_uuid(), 'lubbock sound', 'Lubbock Sound', NOW()),
  (gen_random_uuid(), 'lucknavi thumri', 'Lucknavi Thumri', NOW()),
  (gen_random_uuid(), 'luhya omutibo', 'Luhya Omutibo', NOW()),
  (gen_random_uuid(), 'luk grung', 'Luk Grung', NOW()),
  (gen_random_uuid(), 'lullaby', 'Lullaby', NOW()),
  (gen_random_uuid(), 'lundu', 'Lundu', NOW()),
  (gen_random_uuid(), 'lundum', 'Lundum', NOW()),
  (gen_random_uuid(), 'm-base', 'M-base', NOW()),
  (gen_random_uuid(), 'madchester', 'Madchester', NOW()),
  (gen_random_uuid(), 'madrigal', 'Madrigal', NOW()),
  (gen_random_uuid(), 'mafioso rap', 'Mafioso Rap', NOW()),
  (gen_random_uuid(), 'maglaal', 'Maglaal', NOW()),
  (gen_random_uuid(), 'magnificat', 'Magnificat', NOW()),
  (gen_random_uuid(), 'mahori', 'Mahori', NOW()),
  (gen_random_uuid(), 'mainstream jazz', 'Mainstream Jazz', NOW()),
  (gen_random_uuid(), 'makossa', 'Makossa', NOW()),
  (gen_random_uuid(), 'makossa-soukous', 'Makossa-soukous', NOW()),
  (gen_random_uuid(), 'malagueñas', 'Malagueñas', NOW()),
  (gen_random_uuid(), 'malawian jazz', 'Malawian Jazz', NOW()),
  (gen_random_uuid(), 'malhun', 'Malhun', NOW()),
  (gen_random_uuid(), 'maloya', 'Maloya', NOW()),
  (gen_random_uuid(), 'maluf', 'Maluf', NOW()),
  (gen_random_uuid(), 'maluka', 'Maluka', NOW()),
  (gen_random_uuid(), 'mambo', 'Mambo', NOW()),
  (gen_random_uuid(), 'manaschi', 'Manaschi', NOW()),
  (gen_random_uuid(), 'mandarin pop', 'Mandarin Pop', NOW()),
  (gen_random_uuid(), 'manding swing', 'Manding Swing', NOW()),
  (gen_random_uuid(), 'mango', 'Mango', NOW()),
  (gen_random_uuid(), 'mangue bit', 'Mangue Bit', NOW()),
  (gen_random_uuid(), 'mangulina', 'Mangulina', NOW()),
  (gen_random_uuid(), 'manikay', 'Manikay', NOW()),
  (gen_random_uuid(), 'manila sound', 'Manila Sound', NOW()),
  (gen_random_uuid(), 'manouche', 'Manouche', NOW()),
  (gen_random_uuid(), 'manzuma', 'Manzuma', NOW()),
  (gen_random_uuid(), 'mapouka', 'Mapouka', NOW()),
  (gen_random_uuid(), 'mapouka-serré', 'Mapouka-serré', NOW()),
  (gen_random_uuid(), 'marabi', 'Marabi', NOW()),
  (gen_random_uuid(), 'maracatu', 'Maracatu', NOW()),
  (gen_random_uuid(), 'marga', 'Marga', NOW()),
  (gen_random_uuid(), 'mariachi', 'Mariachi', NOW()),
  (gen_random_uuid(), 'marimba', 'Marimba', NOW()),
  (gen_random_uuid(), 'marinera', 'Marinera', NOW()),
  (gen_random_uuid(), 'marrabenta', 'Marrabenta', NOW()),
  (gen_random_uuid(), 'martial industrial', 'Martial Industrial', NOW()),
  (gen_random_uuid(), 'martinetes', 'Martinetes', NOW()),
  (gen_random_uuid(), 'maskanda', 'Maskanda', NOW()),
  (gen_random_uuid(), 'mass', 'Mass', NOW()),
  (gen_random_uuid(), 'matamuerte', 'Matamuerte', NOW()),
  (gen_random_uuid(), 'math rock', 'Math Rock', NOW()),
  (gen_random_uuid(), 'mathcore', 'Mathcore', NOW()),
  (gen_random_uuid(), 'matt bello', 'Matt Bello', NOW()),
  (gen_random_uuid(), 'maxixe', 'Maxixe', NOW()),
  (gen_random_uuid(), 'mazurka', 'Mazurka', NOW()),
  (gen_random_uuid(), 'mbalax', 'Mbalax', NOW()),
  (gen_random_uuid(), 'mbaqanga', 'Mbaqanga', NOW()),
  (gen_random_uuid(), 'mbube', 'Mbube', NOW()),
  (gen_random_uuid(), 'mbumba', 'Mbumba', NOW()),
  (gen_random_uuid(), 'medh', 'Medh', NOW()),
  (gen_random_uuid(), 'medieval folk rock', 'Medieval Folk Rock', NOW()),
  (gen_random_uuid(), 'medieval metal', 'Medieval Metal', NOW()),
  (gen_random_uuid(), 'medieval music', 'Medieval Music', NOW()),
  (gen_random_uuid(), 'meditation', 'Meditation', NOW()),
  (gen_random_uuid(), 'mejorana', 'Mejorana', NOW()),
  (gen_random_uuid(), 'melhoun', 'Melhoun', NOW()),
  (gen_random_uuid(), 'melhûn', 'Melhûn', NOW()),
  (gen_random_uuid(), 'melodic black metal', 'Melodic Black Metal', NOW()),
  (gen_random_uuid(), 'melodic death metal', 'Melodic Death Metal', NOW()),
  (gen_random_uuid(), 'melodic hardcore', 'Melodic Hardcore', NOW()),
  (gen_random_uuid(), 'melodic metalcore', 'Melodic Metalcore', NOW()),
  (gen_random_uuid(), 'melodic music', 'Melodic Music', NOW()),
  (gen_random_uuid(), 'melodic trance', 'Melodic Trance', NOW()),
  (gen_random_uuid(), 'memphis blues', 'Memphis Blues', NOW()),
  (gen_random_uuid(), 'memphis rap', 'Memphis Rap', NOW()),
  (gen_random_uuid(), 'memphis soul', 'Memphis Soul', NOW()),
  (gen_random_uuid(), 'mento', 'Mento', NOW()),
  (gen_random_uuid(), 'merengue', 'Merengue', NOW()),
  (gen_random_uuid(), 'merengue típico moderno', 'Merengue Típico Moderno', NOW()),
  (gen_random_uuid(), 'merengue-bomba', 'Merengue-bomba', NOW()),
  (gen_random_uuid(), 'meringue', 'Meringue', NOW()),
  (gen_random_uuid(), 'merseybeat', 'Merseybeat', NOW()),
  (gen_random_uuid(), 'metal', 'Metal', NOW()),
  (gen_random_uuid(), 'metalcore', 'Metalcore', NOW()),
  (gen_random_uuid(), 'metallic hardcore', 'Metallic Hardcore', NOW()),
  (gen_random_uuid(), 'mexican pop', 'Mexican Pop', NOW()),
  (gen_random_uuid(), 'mexican rock', 'Mexican Rock', NOW()),
  (gen_random_uuid(), 'mexican son', 'Mexican Son', NOW()),
  (gen_random_uuid(), 'meykhana', 'Meykhana', NOW()),
  (gen_random_uuid(), 'mezwed', 'Mezwed', NOW()),
  (gen_random_uuid(), 'miami bass', 'Miami Bass', NOW()),
  (gen_random_uuid(), 'microhouse', 'Microhouse', NOW()),
  (gen_random_uuid(), 'middle of the road', 'Middle Of The Road', NOW()),
  (gen_random_uuid(), 'midwest hip hop', 'Midwest Hip Hop', NOW()),
  (gen_random_uuid(), 'milonga', 'Milonga', NOW()),
  (gen_random_uuid(), 'min''yo', 'Min''yo', NOW()),
  (gen_random_uuid(), 'mineras', 'Mineras', NOW()),
  (gen_random_uuid(), 'mini compas', 'Mini Compas', NOW()),
  (gen_random_uuid(), 'mini-jazz', 'Mini-jazz', NOW()),
  (gen_random_uuid(), 'minimal techno', 'Minimal Techno', NOW()),
  (gen_random_uuid(), 'minimalist music', 'Minimalist Music', NOW()),
  (gen_random_uuid(), 'minimalist trance', 'Minimalist Trance', NOW()),
  (gen_random_uuid(), 'minneapolis sound', 'Minneapolis Sound', NOW()),
  (gen_random_uuid(), 'minstrel show', 'Minstrel Show', NOW()),
  (gen_random_uuid(), 'minuet', 'Minuet', NOW()),
  (gen_random_uuid(), 'mirolóyia', 'Mirolóyia', NOW()),
  (gen_random_uuid(), 'modal jazz', 'Modal Jazz', NOW()),
  (gen_random_uuid(), 'modern classical', 'Modern Classical', NOW()),
  (gen_random_uuid(), 'modern classical music', 'Modern Classical Music', NOW()),
  (gen_random_uuid(), 'modern laika', 'Modern Laika', NOW()),
  (gen_random_uuid(), 'modern rock', 'Modern Rock', NOW()),
  (gen_random_uuid(), 'modinha', 'Modinha', NOW()),
  (gen_random_uuid(), 'mohabelo', 'Mohabelo', NOW()),
  (gen_random_uuid(), 'montuno', 'Montuno', NOW()),
  (gen_random_uuid(), 'monumental dance', 'Monumental Dance', NOW()),
  (gen_random_uuid(), 'mor lam', 'Mor Lam', NOW()),
  (gen_random_uuid(), 'mor lam sing', 'Mor Lam Sing', NOW()),
  (gen_random_uuid(), 'morna', 'Morna', NOW()),
  (gen_random_uuid(), 'motorpop', 'Motorpop', NOW()),
  (gen_random_uuid(), 'motown', 'Motown', NOW()),
  (gen_random_uuid(), 'mozambique', 'Mozambique', NOW()),
  (gen_random_uuid(), 'mpb', 'Mpb', NOW()),
  (gen_random_uuid(), 'mugam', 'Mugam', NOW()),
  (gen_random_uuid(), 'multicultural', 'Multicultural', NOW()),
  (gen_random_uuid(), 'murga', 'Murga', NOW()),
  (gen_random_uuid(), 'musette', 'Musette', NOW()),
  (gen_random_uuid(), 'museve', 'Museve', NOW()),
  (gen_random_uuid(), 'mushroom jazz', 'Mushroom Jazz', NOW()),
  (gen_random_uuid(), 'music drama', 'Music Drama', NOW()),
  (gen_random_uuid(), 'music hall', 'Music Hall', NOW()),
  (gen_random_uuid(), 'musiqi-e assil', 'Musiqi-e Assil', NOW()),
  (gen_random_uuid(), 'musique concrète', 'Musique Concrète', NOW()),
  (gen_random_uuid(), 'mutuashi', 'Mutuashi', NOW()),
  (gen_random_uuid(), 'muwashshah', 'Muwashshah', NOW()),
  (gen_random_uuid(), 'muzak', 'Muzak', NOW()),
  (gen_random_uuid(), 'méringue', 'Méringue', NOW()),
  (gen_random_uuid(), 'música campesina', 'Música Campesina', NOW()),
  (gen_random_uuid(), 'música criolla', 'Música Criolla', NOW()),
  (gen_random_uuid(), 'música de la interior', 'Música De La Interior', NOW()),
  (gen_random_uuid(), 'música llanera', 'Música Llanera', NOW()),
  (gen_random_uuid(), 'música nordestina', 'Música Nordestina', NOW()),
  (gen_random_uuid(), 'música popular brasileira', 'Música Popular Brasileira', NOW()),
  (gen_random_uuid(), 'música tropical', 'Música Tropical', NOW()),
  (gen_random_uuid(), 'nagauta', 'Nagauta', NOW()),
  (gen_random_uuid(), 'nakasi', 'Nakasi', NOW()),
  (gen_random_uuid(), 'nangma', 'Nangma', NOW()),
  (gen_random_uuid(), 'nanguan', 'Nanguan', NOW()),
  (gen_random_uuid(), 'narcocorrido', 'Narcocorrido', NOW()),
  (gen_random_uuid(), 'nardcore', 'Nardcore', NOW()),
  (gen_random_uuid(), 'narodna muzika', 'Narodna Muzika', NOW()),
  (gen_random_uuid(), 'nasheed', 'Nasheed', NOW()),
  (gen_random_uuid(), 'nashville sound', 'Nashville Sound', NOW()),
  (gen_random_uuid(), 'nashville sound/countrypolitan', 'Nashville Sound/countrypolitan', NOW()),
  (gen_random_uuid(), 'national socialist black metal', 'National Socialist Black Metal', NOW()),
  (gen_random_uuid(), 'naturalismo', 'Naturalismo', NOW()),
  (gen_random_uuid(), 'nederpop', 'Nederpop', NOW()),
  (gen_random_uuid(), 'neo soul', 'Neo Soul', NOW()),
  (gen_random_uuid(), 'neo-classical metal', 'Neo-classical Metal', NOW()),
  (gen_random_uuid(), 'neo-medieval', 'Neo-medieval', NOW()),
  (gen_random_uuid(), 'neo-prog', 'Neo-prog', NOW()),
  (gen_random_uuid(), 'neo-psychedelia', 'Neo-psychedelia', NOW()),
  (gen_random_uuid(), 'neoclassical', 'Neoclassical', NOW()),
  (gen_random_uuid(), 'neoclassical metal', 'Neoclassical Metal', NOW()),
  (gen_random_uuid(), 'neoclassical music', 'Neoclassical Music', NOW()),
  (gen_random_uuid(), 'neofolk', 'Neofolk', NOW()),
  (gen_random_uuid(), 'neotraditional country', 'Neotraditional Country', NOW()),
  (gen_random_uuid(), 'nerdcore', 'Nerdcore', NOW()),
  (gen_random_uuid(), 'neue deutsche härte', 'Neue Deutsche Härte', NOW()),
  (gen_random_uuid(), 'neue deutsche welle', 'Neue Deutsche Welle', NOW()),
  (gen_random_uuid(), 'new age music', 'New Age Music', NOW()),
  (gen_random_uuid(), 'new beat', 'New Beat', NOW()),
  (gen_random_uuid(), 'new instrumental', 'New Instrumental', NOW()),
  (gen_random_uuid(), 'new jack swing', 'New Jack Swing', NOW()),
  (gen_random_uuid(), 'new orleans blues', 'New Orleans Blues', NOW()),
  (gen_random_uuid(), 'new orleans jazz', 'New Orleans Jazz', NOW()),
  (gen_random_uuid(), 'new pop', 'New Pop', NOW()),
  (gen_random_uuid(), 'new prog', 'New Prog', NOW()),
  (gen_random_uuid(), 'new rave', 'New Rave', NOW()),
  (gen_random_uuid(), 'new romantic', 'New Romantic', NOW()),
  (gen_random_uuid(), 'new school hip hop', 'New School Hip Hop', NOW()),
  (gen_random_uuid(), 'new taiwanese song', 'New Taiwanese Song', NOW()),
  (gen_random_uuid(), 'new wave', 'New Wave', NOW()),
  (gen_random_uuid(), 'new wave of british heavy metal', 'New Wave Of British Heavy Metal', NOW()),
  (gen_random_uuid(), 'new wave of new wave', 'New Wave Of New Wave', NOW()),
  (gen_random_uuid(), 'new weird america', 'New Weird America', NOW()),
  (gen_random_uuid(), 'new york blues', 'New York Blues', NOW()),
  (gen_random_uuid(), 'new york house', 'New York House', NOW()),
  (gen_random_uuid(), 'newgrass', 'Newgrass', NOW()),
  (gen_random_uuid(), 'nganja', 'Nganja', NOW()),
  (gen_random_uuid(), 'nightcore', 'Nightcore', NOW()),
  (gen_random_uuid(), 'nintendocore', 'Nintendocore', NOW()),
  (gen_random_uuid(), 'nisiótika', 'Nisiótika', NOW()),
  (gen_random_uuid(), 'no wave', 'No Wave', NOW()),
  (gen_random_uuid(), 'noh', 'Noh', NOW()),
  (gen_random_uuid(), 'noise music', 'Noise Music', NOW()),
  (gen_random_uuid(), 'noise pop', 'Noise Pop', NOW()),
  (gen_random_uuid(), 'noise rock', 'Noise Rock', NOW()),
  (gen_random_uuid(), 'nongak', 'Nongak', NOW()),
  (gen_random_uuid(), 'norae undong', 'Norae Undong', NOW()),
  (gen_random_uuid(), 'nordic folk dance music', 'Nordic Folk Dance Music', NOW()),
  (gen_random_uuid(), 'nordic folk music', 'Nordic Folk Music', NOW()),
  (gen_random_uuid(), 'nortec', 'Nortec', NOW()),
  (gen_random_uuid(), 'norteño', 'Norteño', NOW()),
  (gen_random_uuid(), 'northern soul', 'Northern Soul', NOW()),
  (gen_random_uuid(), 'nota', 'Nota', NOW()),
  (gen_random_uuid(), 'nu jazz', 'Nu Jazz', NOW()),
  (gen_random_uuid(), 'nu metal', 'Nu Metal', NOW()),
  (gen_random_uuid(), 'nu soul', 'Nu Soul', NOW()),
  (gen_random_uuid(), 'nu skool breaks', 'Nu Skool Breaks', NOW()),
  (gen_random_uuid(), 'nueva canción', 'Nueva Canción', NOW()),
  (gen_random_uuid(), 'nyatiti', 'Nyatiti', NOW()),
  (gen_random_uuid(), 'néo kýma', 'Néo Kýma', NOW()),
  (gen_random_uuid(), 'obscuro', 'Obscuro', NOW()),
  (gen_random_uuid(), 'oi!', 'Oi!', NOW()),
  (gen_random_uuid(), 'old school hip hop', 'Old School Hip Hop', NOW()),
  (gen_random_uuid(), 'old-time', 'Old-time', NOW()),
  (gen_random_uuid(), 'oldies', 'Oldies', NOW()),
  (gen_random_uuid(), 'olonkho', 'Olonkho', NOW()),
  (gen_random_uuid(), 'oltului', 'Oltului', NOW()),
  (gen_random_uuid(), 'ondo', 'Ondo', NOW()),
  (gen_random_uuid(), 'opera', 'Opera', NOW()),
  (gen_random_uuid(), 'operatic pop', 'Operatic Pop', NOW()),
  (gen_random_uuid(), 'oratorio', 'Oratorio', NOW()),
  (gen_random_uuid(), 'orchestra', 'Orchestra', NOW()),
  (gen_random_uuid(), 'orchestral', 'Orchestral', NOW()),
  (gen_random_uuid(), 'organ trio', 'Organ Trio', NOW()),
  (gen_random_uuid(), 'organic ambient', 'Organic Ambient', NOW()),
  (gen_random_uuid(), 'organum', 'Organum', NOW()),
  (gen_random_uuid(), 'orgel', 'Orgel', NOW()),
  (gen_random_uuid(), 'oriental metal', 'Oriental Metal', NOW()),
  (gen_random_uuid(), 'ottava rima', 'Ottava Rima', NOW()),
  (gen_random_uuid(), 'outlaw country', 'Outlaw Country', NOW()),
  (gen_random_uuid(), 'outsider music', 'Outsider Music', NOW()),
  (gen_random_uuid(), 'p-funk', 'P-funk', NOW()),
  (gen_random_uuid(), 'pagan metal', 'Pagan Metal', NOW()),
  (gen_random_uuid(), 'pagan rock', 'Pagan Rock', NOW()),
  (gen_random_uuid(), 'pagode', 'Pagode', NOW()),
  (gen_random_uuid(), 'paisley underground', 'Paisley Underground', NOW()),
  (gen_random_uuid(), 'palm wine', 'Palm Wine', NOW()),
  (gen_random_uuid(), 'palm-wine', 'Palm-wine', NOW()),
  (gen_random_uuid(), 'pambiche', 'Pambiche', NOW()),
  (gen_random_uuid(), 'panambih', 'Panambih', NOW()),
  (gen_random_uuid(), 'panchai baja', 'Panchai Baja', NOW()),
  (gen_random_uuid(), 'panchavadyam', 'Panchavadyam', NOW()),
  (gen_random_uuid(), 'pansori', 'Pansori', NOW()),
  (gen_random_uuid(), 'paranda', 'Paranda', NOW()),
  (gen_random_uuid(), 'parang', 'Parang', NOW()),
  (gen_random_uuid(), 'parody', 'Parody', NOW()),
  (gen_random_uuid(), 'parranda', 'Parranda', NOW()),
  (gen_random_uuid(), 'partido alto', 'Partido Alto', NOW()),
  (gen_random_uuid(), 'pasillo', 'Pasillo', NOW()),
  (gen_random_uuid(), 'patriotic', 'Patriotic', NOW()),
  (gen_random_uuid(), 'peace punk', 'Peace Punk', NOW()),
  (gen_random_uuid(), 'pelimanni music', 'Pelimanni Music', NOW()),
  (gen_random_uuid(), 'petenera', 'Petenera', NOW()),
  (gen_random_uuid(), 'peyote song', 'Peyote Song', NOW()),
  (gen_random_uuid(), 'philadelphia soul', 'Philadelphia Soul', NOW()),
  (gen_random_uuid(), 'piano blues', 'Piano Blues', NOW()),
  (gen_random_uuid(), 'piano rock', 'Piano Rock', NOW()),
  (gen_random_uuid(), 'piedmont blues', 'Piedmont Blues', NOW()),
  (gen_random_uuid(), 'pimba', 'Pimba', NOW()),
  (gen_random_uuid(), 'pinoy pop', 'Pinoy Pop', NOW()),
  (gen_random_uuid(), 'pinoy rock', 'Pinoy Rock', NOW()),
  (gen_random_uuid(), 'pinpeat orchestra', 'Pinpeat Orchestra', NOW()),
  (gen_random_uuid(), 'piphat', 'Piphat', NOW()),
  (gen_random_uuid(), 'piyyutim', 'Piyyutim', NOW()),
  (gen_random_uuid(), 'plainchant', 'Plainchant', NOW()),
  (gen_random_uuid(), 'plena', 'Plena', NOW()),
  (gen_random_uuid(), 'pleng phua cheewit', 'Pleng Phua Cheewit', NOW()),
  (gen_random_uuid(), 'pleng thai sakorn', 'Pleng Thai Sakorn', NOW()),
  (gen_random_uuid(), 'political hip hop', 'Political Hip Hop', NOW()),
  (gen_random_uuid(), 'polka', 'Polka', NOW()),
  (gen_random_uuid(), 'polo', 'Polo', NOW()),
  (gen_random_uuid(), 'polonaise', 'Polonaise', NOW()),
  (gen_random_uuid(), 'pols', 'Pols', NOW()),
  (gen_random_uuid(), 'polska', 'Polska', NOW()),
  (gen_random_uuid(), 'pong lang', 'Pong Lang', NOW()),
  (gen_random_uuid(), 'pop', 'Pop', NOW()),
  (gen_random_uuid(), 'pop folk', 'Pop Folk', NOW()),
  (gen_random_uuid(), 'pop music', 'Pop Music', NOW()),
  (gen_random_uuid(), 'pop punk', 'Pop Punk', NOW()),
  (gen_random_uuid(), 'pop rap', 'Pop Rap', NOW()),
  (gen_random_uuid(), 'pop rock', 'Pop Rock', NOW()),
  (gen_random_uuid(), 'pop sunda', 'Pop Sunda', NOW()),
  (gen_random_uuid(), 'pornocore', 'Pornocore', NOW()),
  (gen_random_uuid(), 'porro', 'Porro', NOW()),
  (gen_random_uuid(), 'post disco', 'Post Disco', NOW()),
  (gen_random_uuid(), 'post-britpop', 'Post-britpop', NOW()),
  (gen_random_uuid(), 'post-disco', 'Post-disco', NOW()),
  (gen_random_uuid(), 'post-grunge', 'Post-grunge', NOW()),
  (gen_random_uuid(), 'post-hardcore', 'Post-hardcore', NOW()),
  (gen_random_uuid(), 'post-industrial', 'Post-industrial', NOW()),
  (gen_random_uuid(), 'post-metal', 'Post-metal', NOW()),
  (gen_random_uuid(), 'post-minimalism', 'Post-minimalism', NOW()),
  (gen_random_uuid(), 'post-punk', 'Post-punk', NOW()),
  (gen_random_uuid(), 'post-rock', 'Post-rock', NOW()),
  (gen_random_uuid(), 'post-romanticism', 'Post-romanticism', NOW()),
  (gen_random_uuid(), 'pow-wow', 'Pow-wow', NOW()),
  (gen_random_uuid(), 'power electronics', 'Power Electronics', NOW()),
  (gen_random_uuid(), 'power metal', 'Power Metal', NOW()),
  (gen_random_uuid(), 'power noise', 'Power Noise', NOW()),
  (gen_random_uuid(), 'power pop', 'Power Pop', NOW()),
  (gen_random_uuid(), 'powerviolence', 'Powerviolence', NOW()),
  (gen_random_uuid(), 'ppongtchak', 'Ppongtchak', NOW()),
  (gen_random_uuid(), 'praise song', 'Praise Song', NOW()),
  (gen_random_uuid(), 'program symphony', 'Program Symphony', NOW()),
  (gen_random_uuid(), 'progressive bluegrass', 'Progressive Bluegrass', NOW()),
  (gen_random_uuid(), 'progressive country', 'Progressive Country', NOW()),
  (gen_random_uuid(), 'progressive death metal', 'Progressive Death Metal', NOW()),
  (gen_random_uuid(), 'progressive electronic', 'Progressive Electronic', NOW()),
  (gen_random_uuid(), 'progressive electronic music', 'Progressive Electronic Music', NOW()),
  (gen_random_uuid(), 'progressive folk', 'Progressive Folk', NOW()),
  (gen_random_uuid(), 'progressive folk music', 'Progressive Folk Music', NOW()),
  (gen_random_uuid(), 'progressive house', 'Progressive House', NOW()),
  (gen_random_uuid(), 'progressive metal', 'Progressive Metal', NOW()),
  (gen_random_uuid(), 'progressive power metal', 'Progressive Power Metal', NOW()),
  (gen_random_uuid(), 'progressive rock', 'Progressive Rock', NOW()),
  (gen_random_uuid(), 'progressive trance', 'Progressive Trance', NOW()),
  (gen_random_uuid(), 'progressive thrash metal', 'Progressive Thrash Metal', NOW()),
  (gen_random_uuid(), 'protopunk', 'Protopunk', NOW()),
  (gen_random_uuid(), 'psych folk', 'Psych Folk', NOW()),
  (gen_random_uuid(), 'psychedelic music', 'Psychedelic Music', NOW()),
  (gen_random_uuid(), 'psychedelic pop', 'Psychedelic Pop', NOW()),
  (gen_random_uuid(), 'psychedelic rock', 'Psychedelic Rock', NOW()),
  (gen_random_uuid(), 'psychedelic trance', 'Psychedelic Trance', NOW()),
  (gen_random_uuid(), 'psychobilly', 'Psychobilly', NOW()),
  (gen_random_uuid(), 'punk blues', 'Punk Blues', NOW()),
  (gen_random_uuid(), 'punk cabaret', 'Punk Cabaret', NOW()),
  (gen_random_uuid(), 'punk jazz', 'Punk Jazz', NOW()),
  (gen_random_uuid(), 'punk rock', 'Punk Rock', NOW()),
  (gen_random_uuid(), 'punta', 'Punta', NOW()),
  (gen_random_uuid(), 'punta rock', 'Punta Rock', NOW()),
  (gen_random_uuid(), 'qasidah', 'Qasidah', NOW()),
  (gen_random_uuid(), 'qasidah modern', 'Qasidah Modern', NOW()),
  (gen_random_uuid(), 'qawwali', 'Qawwali', NOW()),
  (gen_random_uuid(), 'quadrille', 'Quadrille', NOW()),
  (gen_random_uuid(), 'quan ho', 'Quan Ho', NOW()),
  (gen_random_uuid(), 'queercore', 'Queercore', NOW()),
  (gen_random_uuid(), 'quiet storm', 'Quiet Storm', NOW()),
  (gen_random_uuid(), 'rada', 'Rada', NOW()),
  (gen_random_uuid(), 'raga', 'Raga', NOW()),
  (gen_random_uuid(), 'raga rock', 'Raga Rock', NOW()),
  (gen_random_uuid(), 'ragga', 'Ragga', NOW()),
  (gen_random_uuid(), 'ragga jungle', 'Ragga Jungle', NOW()),
  (gen_random_uuid(), 'raggamuffin', 'Raggamuffin', NOW()),
  (gen_random_uuid(), 'ragtime', 'Ragtime', NOW()),
  (gen_random_uuid(), 'rai', 'Rai', NOW()),
  (gen_random_uuid(), 'rake-and-scrape', 'Rake-and-scrape', NOW()),
  (gen_random_uuid(), 'ramkbach', 'Ramkbach', NOW()),
  (gen_random_uuid(), 'ramvong', 'Ramvong', NOW()),
  (gen_random_uuid(), 'ranchera', 'Ranchera', NOW()),
  (gen_random_uuid(), 'rap', 'Rap', NOW()),
  (gen_random_uuid(), 'rap metal', 'Rap Metal', NOW()),
  (gen_random_uuid(), 'rap rock', 'Rap Rock', NOW()),
  (gen_random_uuid(), 'rapcore', 'Rapcore', NOW()),
  (gen_random_uuid(), 'rara', 'Rara', NOW()),
  (gen_random_uuid(), 'rare groove', 'Rare Groove', NOW()),
  (gen_random_uuid(), 'rasiya', 'Rasiya', NOW()),
  (gen_random_uuid(), 'rave', 'Rave', NOW()),
  (gen_random_uuid(), 'raw rock', 'Raw Rock', NOW()),
  (gen_random_uuid(), 'raï', 'Raï', NOW()),
  (gen_random_uuid(), 'rebetiko', 'Rebetiko', NOW()),
  (gen_random_uuid(), 'red dirt', 'Red Dirt', NOW()),
  (gen_random_uuid(), 'reel', 'Reel', NOW()),
  (gen_random_uuid(), 'reggae', 'Reggae', NOW()),
  (gen_random_uuid(), 'reggae 110', 'Reggae 110', NOW()),
  (gen_random_uuid(), 'reggae bultrón', 'Reggae Bultrón', NOW()),
  (gen_random_uuid(), 'reggae en español', 'Reggae En Español', NOW()),
  (gen_random_uuid(), 'reggae fusion', 'Reggae Fusion', NOW()),
  (gen_random_uuid(), 'reggae highlife', 'Reggae Highlife', NOW()),
  (gen_random_uuid(), 'reggaefusion', 'Reggaefusion', NOW()),
  (gen_random_uuid(), 'reggaeton', 'Reggaeton', NOW()),
  (gen_random_uuid(), 'rekilaulu', 'Rekilaulu', NOW()),
  (gen_random_uuid(), 'relax music', 'Relax Music', NOW()),
  (gen_random_uuid(), 'religious', 'Religious', NOW()),
  (gen_random_uuid(), 'rembetiko', 'Rembetiko', NOW()),
  (gen_random_uuid(), 'renaissance music', 'Renaissance Music', NOW()),
  (gen_random_uuid(), 'requiem', 'Requiem', NOW()),
  (gen_random_uuid(), 'rhapsody', 'Rhapsody', NOW()),
  (gen_random_uuid(), 'rhyming spiritual', 'Rhyming Spiritual', NOW()),
  (gen_random_uuid(), 'rhythm & blues', 'Rhythm & Blues', NOW()),
  (gen_random_uuid(), 'rhythm and blues', 'Rhythm And Blues', NOW()),
  (gen_random_uuid(), 'ricercar', 'Ricercar', NOW()),
  (gen_random_uuid(), 'riot grrrl', 'Riot Grrrl', NOW()),
  (gen_random_uuid(), 'rock', 'Rock', NOW()),
  (gen_random_uuid(), 'rock and roll', 'Rock And Roll', NOW()),
  (gen_random_uuid(), 'rock en español', 'Rock En Español', NOW()),
  (gen_random_uuid(), 'rock opera', 'Rock Opera', NOW()),
  (gen_random_uuid(), 'rockabilly', 'Rockabilly', NOW()),
  (gen_random_uuid(), 'rocksteady', 'Rocksteady', NOW()),
  (gen_random_uuid(), 'rococo', 'Rococo', NOW()),
  (gen_random_uuid(), 'romantic flow', 'Romantic Flow', NOW()),
  (gen_random_uuid(), 'romantic period in music', 'Romantic Period In Music', NOW()),
  (gen_random_uuid(), 'rondeaux', 'Rondeaux', NOW()),
  (gen_random_uuid(), 'ronggeng', 'Ronggeng', NOW()),
  (gen_random_uuid(), 'roots reggae', 'Roots Reggae', NOW()),
  (gen_random_uuid(), 'roots rock', 'Roots Rock', NOW()),
  (gen_random_uuid(), 'roots rock reggae', 'Roots Rock Reggae', NOW()),
  (gen_random_uuid(), 'rumba', 'Rumba', NOW()),
  (gen_random_uuid(), 'russian pop', 'Russian Pop', NOW()),
  (gen_random_uuid(), 'rímur', 'Rímur', NOW()),
  (gen_random_uuid(), 'sabar', 'Sabar', NOW()),
  (gen_random_uuid(), 'sacred harp', 'Sacred Harp', NOW()),
  (gen_random_uuid(), 'sacred music', 'Sacred Music', NOW()),
  (gen_random_uuid(), 'sadcore', 'Sadcore', NOW()),
  (gen_random_uuid(), 'saibara', 'Saibara', NOW()),
  (gen_random_uuid(), 'sakara', 'Sakara', NOW()),
  (gen_random_uuid(), 'salegy', 'Salegy', NOW()),
  (gen_random_uuid(), 'salsa', 'Salsa', NOW()),
  (gen_random_uuid(), 'salsa erotica', 'Salsa Erotica', NOW()),
  (gen_random_uuid(), 'salsa romantica', 'Salsa Romantica', NOW()),
  (gen_random_uuid(), 'saltarello', 'Saltarello', NOW()),
  (gen_random_uuid(), 'samba', 'Samba', NOW()),
  (gen_random_uuid(), 'samba-canção', 'Samba-canção', NOW()),
  (gen_random_uuid(), 'samba-reggae', 'Samba-reggae', NOW()),
  (gen_random_uuid(), 'samba-rock', 'Samba-rock', NOW()),
  (gen_random_uuid(), 'sambai', 'Sambai', NOW()),
  (gen_random_uuid(), 'sanjo', 'Sanjo', NOW()),
  (gen_random_uuid(), 'sato kagura', 'Sato Kagura', NOW()),
  (gen_random_uuid(), 'sawt', 'Sawt', NOW()),
  (gen_random_uuid(), 'saya', 'Saya', NOW()),
  (gen_random_uuid(), 'scat', 'Scat', NOW()),
  (gen_random_uuid(), 'schlager', 'Schlager', NOW()),
  (gen_random_uuid(), 'schottisch', 'Schottisch', NOW()),
  (gen_random_uuid(), 'schranz', 'Schranz', NOW()),
  (gen_random_uuid(), 'scottish baroque music', 'Scottish Baroque Music', NOW()),
  (gen_random_uuid(), 'screamo', 'Screamo', NOW()),
  (gen_random_uuid(), 'scrumpy and western', 'Scrumpy And Western', NOW()),
  (gen_random_uuid(), 'sea shanty', 'Sea Shanty', NOW()),
  (gen_random_uuid(), 'sean nós', 'Sean Nós', NOW()),
  (gen_random_uuid(), 'second viennese school', 'Second Viennese School', NOW()),
  (gen_random_uuid(), 'sega music', 'Sega Music', NOW()),
  (gen_random_uuid(), 'seggae', 'Seggae', NOW()),
  (gen_random_uuid(), 'seis', 'Seis', NOW()),
  (gen_random_uuid(), 'semba', 'Semba', NOW()),
  (gen_random_uuid(), 'sephardic music', 'Sephardic Music', NOW()),
  (gen_random_uuid(), 'serialism', 'Serialism', NOW()),
  (gen_random_uuid(), 'set dance', 'Set Dance', NOW()),
  (gen_random_uuid(), 'sevdalinka', 'Sevdalinka', NOW()),
  (gen_random_uuid(), 'sevillana', 'Sevillana', NOW()),
  (gen_random_uuid(), 'shabab', 'Shabab', NOW()),
  (gen_random_uuid(), 'shabad', 'Shabad', NOW()),
  (gen_random_uuid(), 'shalako', 'Shalako', NOW()),
  (gen_random_uuid(), 'shan''ge', 'Shan''ge', NOW()),
  (gen_random_uuid(), 'shango', 'Shango', NOW()),
  (gen_random_uuid(), 'shape note', 'Shape Note', NOW()),
  (gen_random_uuid(), 'shibuya-kei', 'Shibuya-kei', NOW()),
  (gen_random_uuid(), 'shidaiqu', 'Shidaiqu', NOW()),
  (gen_random_uuid(), 'shima uta', 'Shima Uta', NOW()),
  (gen_random_uuid(), 'shock rock', 'Shock Rock', NOW()),
  (gen_random_uuid(), 'shoegaze', 'Shoegaze', NOW()),
  (gen_random_uuid(), 'shoegazer', 'Shoegazer', NOW()),
  (gen_random_uuid(), 'shoka', 'Shoka', NOW()),
  (gen_random_uuid(), 'shomyo', 'Shomyo', NOW()),
  (gen_random_uuid(), 'show tune', 'Show Tune', NOW()),
  (gen_random_uuid(), 'sica', 'Sica', NOW()),
  (gen_random_uuid(), 'siguiriyas', 'Siguiriyas', NOW()),
  (gen_random_uuid(), 'silat', 'Silat', NOW()),
  (gen_random_uuid(), 'sinawi', 'Sinawi', NOW()),
  (gen_random_uuid(), 'situational', 'Situational', NOW()),
  (gen_random_uuid(), 'ska', 'Ska', NOW()),
  (gen_random_uuid(), 'ska punk', 'Ska Punk', NOW()),
  (gen_random_uuid(), 'skacore', 'Skacore', NOW()),
  (gen_random_uuid(), 'skald', 'Skald', NOW()),
  (gen_random_uuid(), 'skate punk', 'Skate Punk', NOW()),
  (gen_random_uuid(), 'skiffle', 'Skiffle', NOW()),
  (gen_random_uuid(), 'slack-key guitar', 'Slack-key Guitar', NOW()),
  (gen_random_uuid(), 'slide', 'Slide', NOW()),
  (gen_random_uuid(), 'slowcore', 'Slowcore', NOW()),
  (gen_random_uuid(), 'sludge metal', 'Sludge Metal', NOW()),
  (gen_random_uuid(), 'slängpolska', 'Slängpolska', NOW()),
  (gen_random_uuid(), 'smooth jazz', 'Smooth Jazz', NOW()),
  (gen_random_uuid(), 'soca', 'Soca', NOW()),
  (gen_random_uuid(), 'soft rock', 'Soft Rock', NOW()),
  (gen_random_uuid(), 'son', 'Son', NOW()),
  (gen_random_uuid(), 'son montuno', 'Son Montuno', NOW()),
  (gen_random_uuid(), 'son-batá', 'Son-batá', NOW()),
  (gen_random_uuid(), 'sonata', 'Sonata', NOW()),
  (gen_random_uuid(), 'songo', 'Songo', NOW()),
  (gen_random_uuid(), 'songo-salsa', 'Songo-salsa', NOW()),
  (gen_random_uuid(), 'sophisti-pop', 'Sophisti-pop', NOW()),
  (gen_random_uuid(), 'soukous', 'Soukous', NOW()),
  (gen_random_uuid(), 'soul', 'Soul', NOW()),
  (gen_random_uuid(), 'soul blues', 'Soul Blues', NOW()),
  (gen_random_uuid(), 'soul jazz', 'Soul Jazz', NOW()),
  (gen_random_uuid(), 'soul music', 'Soul Music', NOW()),
  (gen_random_uuid(), 'southern gospel', 'Southern Gospel', NOW()),
  (gen_random_uuid(), 'southern harmony', 'Southern Harmony', NOW()),
  (gen_random_uuid(), 'southern hip hop', 'Southern Hip Hop', NOW()),
  (gen_random_uuid(), 'southern metal', 'Southern Metal', NOW()),
  (gen_random_uuid(), 'southern rock', 'Southern Rock', NOW()),
  (gen_random_uuid(), 'southern soul', 'Southern Soul', NOW()),
  (gen_random_uuid(), 'space age pop', 'Space Age Pop', NOW()),
  (gen_random_uuid(), 'space music', 'Space Music', NOW()),
  (gen_random_uuid(), 'space rock', 'Space Rock', NOW()),
  (gen_random_uuid(), 'spectralism', 'Spectralism', NOW()),
  (gen_random_uuid(), 'speed garage', 'Speed Garage', NOW()),
  (gen_random_uuid(), 'speed metal', 'Speed Metal', NOW()),
  (gen_random_uuid(), 'speedcore', 'Speedcore', NOW()),
  (gen_random_uuid(), 'spirituals', 'Spirituals', NOW()),
  (gen_random_uuid(), 'spouge', 'Spouge', NOW()),
  (gen_random_uuid(), 'sprechgesang', 'Sprechgesang', NOW()),
  (gen_random_uuid(), 'square dance', 'Square Dance', NOW()),
  (gen_random_uuid(), 'squee', 'Squee', NOW()),
  (gen_random_uuid(), 'st. louis blues', 'St. Louis Blues', NOW()),
  (gen_random_uuid(), 'stand-up', 'Stand-up', NOW()),
  (gen_random_uuid(), 'steelband', 'Steelband', NOW()),
  (gen_random_uuid(), 'stoner metal', 'Stoner Metal', NOW()),
  (gen_random_uuid(), 'stoner rock', 'Stoner Rock', NOW()),
  (gen_random_uuid(), 'straight edge', 'Straight Edge', NOW()),
  (gen_random_uuid(), 'strathspeys', 'Strathspeys', NOW()),
  (gen_random_uuid(), 'stride', 'Stride', NOW()),
  (gen_random_uuid(), 'string', 'String', NOW()),
  (gen_random_uuid(), 'string quartet', 'String Quartet', NOW()),
  (gen_random_uuid(), 'sufi music', 'Sufi Music', NOW()),
  (gen_random_uuid(), 'suite', 'Suite', NOW()),
  (gen_random_uuid(), 'sunshine pop', 'Sunshine Pop', NOW()),
  (gen_random_uuid(), 'suomirock', 'Suomirock', NOW()),
  (gen_random_uuid(), 'super eurobeat', 'Super Eurobeat', NOW()),
  (gen_random_uuid(), 'surf ballad', 'Surf Ballad', NOW()),
  (gen_random_uuid(), 'surf instrumental', 'Surf Instrumental', NOW()),
  (gen_random_uuid(), 'surf music', 'Surf Music', NOW()),
  (gen_random_uuid(), 'surf pop', 'Surf Pop', NOW()),
  (gen_random_uuid(), 'surf rock', 'Surf Rock', NOW()),
  (gen_random_uuid(), 'swamp blues', 'Swamp Blues', NOW()),
  (gen_random_uuid(), 'swamp pop', 'Swamp Pop', NOW()),
  (gen_random_uuid(), 'swamp rock', 'Swamp Rock', NOW()),
  (gen_random_uuid(), 'swing', 'Swing', NOW()),
  (gen_random_uuid(), 'swing music', 'Swing Music', NOW()),
  (gen_random_uuid(), 'swingbeat', 'Swingbeat', NOW()),
  (gen_random_uuid(), 'sygyt', 'Sygyt', NOW()),
  (gen_random_uuid(), 'symphonic', 'Symphonic', NOW()),
  (gen_random_uuid(), 'symphonic black metal', 'Symphonic Black Metal', NOW()),
  (gen_random_uuid(), 'symphonic metal', 'Symphonic Metal', NOW()),
  (gen_random_uuid(), 'symphonic poem', 'Symphonic Poem', NOW()),
  (gen_random_uuid(), 'symphonic rock', 'Symphonic Rock', NOW()),
  (gen_random_uuid(), 'symphony', 'Symphony', NOW()),
  (gen_random_uuid(), 'synthcore', 'Synthcore', NOW()),
  (gen_random_uuid(), 'synthpop', 'Synthpop', NOW()),
  (gen_random_uuid(), 'synthpunk', 'Synthpunk', NOW()),
  (gen_random_uuid(), 't''ong guitar', 'T''ong Guitar', NOW()),
  (gen_random_uuid(), 'taarab', 'Taarab', NOW()),
  (gen_random_uuid(), 'tai tu', 'Tai Tu', NOW()),
  (gen_random_uuid(), 'taiwanese pop', 'Taiwanese Pop', NOW()),
  (gen_random_uuid(), 'tala', 'Tala', NOW()),
  (gen_random_uuid(), 'talempong', 'Talempong', NOW()),
  (gen_random_uuid(), 'tambu', 'Tambu', NOW()),
  (gen_random_uuid(), 'tamburitza', 'Tamburitza', NOW()),
  (gen_random_uuid(), 'tamil christian keerthanai', 'Tamil Christian Keerthanai', NOW()),
  (gen_random_uuid(), 'tango', 'Tango', NOW()),
  (gen_random_uuid(), 'tanguk', 'Tanguk', NOW()),
  (gen_random_uuid(), 'tappa', 'Tappa', NOW()),
  (gen_random_uuid(), 'tarana', 'Tarana', NOW()),
  (gen_random_uuid(), 'tarantella', 'Tarantella', NOW()),
  (gen_random_uuid(), 'taranto', 'Taranto', NOW()),
  (gen_random_uuid(), 'tech', 'Tech', NOW()),
  (gen_random_uuid(), 'tech house', 'Tech House', NOW()),
  (gen_random_uuid(), 'tech trance', 'Tech Trance', NOW()),
  (gen_random_uuid(), 'technical death metal', 'Technical Death Metal', NOW()),
  (gen_random_uuid(), 'technical metal', 'Technical Metal', NOW()),
  (gen_random_uuid(), 'techno', 'Techno', NOW()),
  (gen_random_uuid(), 'technoid', 'Technoid', NOW()),
  (gen_random_uuid(), 'technopop', 'Technopop', NOW()),
  (gen_random_uuid(), 'techstep', 'Techstep', NOW()),
  (gen_random_uuid(), 'techtonik', 'Techtonik', NOW()),
  (gen_random_uuid(), 'teen pop', 'Teen Pop', NOW()),
  (gen_random_uuid(), 'tejano', 'Tejano', NOW()),
  (gen_random_uuid(), 'tejano music', 'Tejano Music', NOW()),
  (gen_random_uuid(), 'tekno', 'Tekno', NOW()),
  (gen_random_uuid(), 'tembang sunda', 'Tembang Sunda', NOW()),
  (gen_random_uuid(), 'teutonic thrash metal', 'Teutonic Thrash Metal', NOW()),
  (gen_random_uuid(), 'texas blues', 'Texas Blues', NOW()),
  (gen_random_uuid(), 'thai pop', 'Thai Pop', NOW()),
  (gen_random_uuid(), 'thillana', 'Thillana', NOW()),
  (gen_random_uuid(), 'thrash metal', 'Thrash Metal', NOW()),
  (gen_random_uuid(), 'thrashcore', 'Thrashcore', NOW()),
  (gen_random_uuid(), 'thumri', 'Thumri', NOW()),
  (gen_random_uuid(), 'tibetan pop', 'Tibetan Pop', NOW()),
  (gen_random_uuid(), 'tiento', 'Tiento', NOW()),
  (gen_random_uuid(), 'timbila', 'Timbila', NOW()),
  (gen_random_uuid(), 'tin pan alley', 'Tin Pan Alley', NOW()),
  (gen_random_uuid(), 'tinga', 'Tinga', NOW()),
  (gen_random_uuid(), 'tinku', 'Tinku', NOW()),
  (gen_random_uuid(), 'toeshey', 'Toeshey', NOW()),
  (gen_random_uuid(), 'togaku', 'Togaku', NOW()),
  (gen_random_uuid(), 'trad jazz', 'Trad Jazz', NOW()),
  (gen_random_uuid(), 'traditional bluegrass', 'Traditional Bluegrass', NOW()),
  (gen_random_uuid(), 'traditional heavy metal', 'Traditional Heavy Metal', NOW()),
  (gen_random_uuid(), 'traditional pop music', 'Traditional Pop Music', NOW()),
  (gen_random_uuid(), 'trallalero', 'Trallalero', NOW()),
  (gen_random_uuid(), 'trance', 'Trance', NOW()),
  (gen_random_uuid(), 'tribal house', 'Tribal House', NOW()),
  (gen_random_uuid(), 'trikitixa', 'Trikitixa', NOW()),
  (gen_random_uuid(), 'trip hop', 'Trip Hop', NOW()),
  (gen_random_uuid(), 'trip rock', 'Trip Rock', NOW()),
  (gen_random_uuid(), 'tropicalia', 'Tropicalia', NOW()),
  (gen_random_uuid(), 'tropicalismo', 'Tropicalismo', NOW()),
  (gen_random_uuid(), 'tropipop', 'Tropipop', NOW()),
  (gen_random_uuid(), 'truck-driving country', 'Truck-driving Country', NOW()),
  (gen_random_uuid(), 'tumba', 'Tumba', NOW()),
  (gen_random_uuid(), 'turbo-folk', 'Turbo-folk', NOW()),
  (gen_random_uuid(), 'turkish music', 'Turkish Music', NOW()),
  (gen_random_uuid(), 'turkish pop', 'Turkish Pop', NOW()),
  (gen_random_uuid(), 'turntablism', 'Turntablism', NOW()),
  (gen_random_uuid(), 'tuvan throat-singing', 'Tuvan Throat-singing', NOW()),
  (gen_random_uuid(), 'twee pop', 'Twee Pop', NOW()),
  (gen_random_uuid(), 'twist', 'Twist', NOW()),
  (gen_random_uuid(), 'two tone', 'Two Tone', NOW()),
  (gen_random_uuid(), 'táncház', 'Táncház', NOW()),
  (gen_random_uuid(), 'uk garage', 'Uk Garage', NOW()),
  (gen_random_uuid(), 'uk pub rock', 'Uk Pub Rock', NOW()),
  (gen_random_uuid(), 'unblack metal', 'Unblack Metal', NOW()),
  (gen_random_uuid(), 'underground music', 'Underground Music', NOW()),
  (gen_random_uuid(), 'uplifting', 'Uplifting', NOW()),
  (gen_random_uuid(), 'uplifting trance', 'Uplifting Trance', NOW()),
  (gen_random_uuid(), 'urban cowboy', 'Urban Cowboy', NOW()),
  (gen_random_uuid(), 'urban folk', 'Urban Folk', NOW()),
  (gen_random_uuid(), 'urban jazz', 'Urban Jazz', NOW()),
  (gen_random_uuid(), 'vallenato', 'Vallenato', NOW()),
  (gen_random_uuid(), 'vaudeville', 'Vaudeville', NOW()),
  (gen_random_uuid(), 'venezuela', 'Venezuela', NOW()),
  (gen_random_uuid(), 'verbunkos', 'Verbunkos', NOW()),
  (gen_random_uuid(), 'verismo', 'Verismo', NOW()),
  (gen_random_uuid(), 'viking metal', 'Viking Metal', NOW()),
  (gen_random_uuid(), 'villanella', 'Villanella', NOW()),
  (gen_random_uuid(), 'virelai', 'Virelai', NOW()),
  (gen_random_uuid(), 'vispop', 'Vispop', NOW()),
  (gen_random_uuid(), 'visual kei', 'Visual Kei', NOW()),
  (gen_random_uuid(), 'visual music', 'Visual Music', NOW()),
  (gen_random_uuid(), 'vocal', 'Vocal', NOW()),
  (gen_random_uuid(), 'vocal house', 'Vocal House', NOW()),
  (gen_random_uuid(), 'vocal jazz', 'Vocal Jazz', NOW()),
  (gen_random_uuid(), 'vocal music', 'Vocal Music', NOW()),
  (gen_random_uuid(), 'volksmusik', 'Volksmusik', NOW()),
  (gen_random_uuid(), 'waila', 'Waila', NOW()),
  (gen_random_uuid(), 'waltz', 'Waltz', NOW()),
  (gen_random_uuid(), 'wangga', 'Wangga', NOW()),
  (gen_random_uuid(), 'warabe uta', 'Warabe Uta', NOW()),
  (gen_random_uuid(), 'wassoulou', 'Wassoulou', NOW()),
  (gen_random_uuid(), 'weld', 'Weld', NOW()),
  (gen_random_uuid(), 'were music', 'Were Music', NOW()),
  (gen_random_uuid(), 'west coast hip hop', 'West Coast Hip Hop', NOW()),
  (gen_random_uuid(), 'west coast jazz', 'West Coast Jazz', NOW()),
  (gen_random_uuid(), 'western', 'Western', NOW()),
  (gen_random_uuid(), 'western blues', 'Western Blues', NOW()),
  (gen_random_uuid(), 'western swing', 'Western Swing', NOW()),
  (gen_random_uuid(), 'witch house', 'Witch House', NOW()),
  (gen_random_uuid(), 'wizard rock', 'Wizard Rock', NOW()),
  (gen_random_uuid(), 'women''s music', 'Women''s Music', NOW()),
  (gen_random_uuid(), 'wong shadow', 'Wong Shadow', NOW()),
  (gen_random_uuid(), 'wonky pop', 'Wonky Pop', NOW()),
  (gen_random_uuid(), 'wood', 'Wood', NOW()),
  (gen_random_uuid(), 'work song', 'Work Song', NOW()),
  (gen_random_uuid(), 'world fusion', 'World Fusion', NOW()),
  (gen_random_uuid(), 'world fusion music', 'World Fusion Music', NOW()),
  (gen_random_uuid(), 'world music', 'World Music', NOW()),
  (gen_random_uuid(), 'worldbeat', 'Worldbeat', NOW()),
  (gen_random_uuid(), 'xhosa music', 'Xhosa Music', NOW()),
  (gen_random_uuid(), 'xoomii', 'Xoomii', NOW()),
  (gen_random_uuid(), 'yo-pop', 'Yo-pop', NOW()),
  (gen_random_uuid(), 'yodeling', 'Yodeling', NOW()),
  (gen_random_uuid(), 'yukar', 'Yukar', NOW()),
  (gen_random_uuid(), 'yé-yé', 'Yé-yé', NOW()),
  (gen_random_uuid(), 'zajal', 'Zajal', NOW()),
  (gen_random_uuid(), 'zapin', 'Zapin', NOW()),
  (gen_random_uuid(), 'zarzuela', 'Zarzuela', NOW()),
  (gen_random_uuid(), 'zeibekiko', 'Zeibekiko', NOW()),
  (gen_random_uuid(), 'zeuhl', 'Zeuhl', NOW()),
  (gen_random_uuid(), 'ziglibithy', 'Ziglibithy', NOW()),
  (gen_random_uuid(), 'zouglou', 'Zouglou', NOW()),
  (gen_random_uuid(), 'zouk', 'Zouk', NOW()),
  (gen_random_uuid(), 'zouk chouv', 'Zouk Chouv', NOW()),
  (gen_random_uuid(), 'zouklove', 'Zouklove', NOW()),
  (gen_random_uuid(), 'zulu music', 'Zulu Music', NOW()),
  (gen_random_uuid(), 'zydeco', 'Zydeco', NOW())
ON CONFLICT (name) DO NOTHING;
